### ISSUE TITLE
 an error occurred when running the molecular dynamics simulation

### ISSUE THREAD

**Issue by jkurpost** [haddocking/haddock3#1104]
### Error Description

When running the command `haddock3 mdscoring-test.cfg`, the following error occurred:

```[2024-10-16 10:53:41,601 __init__ INFO] [mdscoring] CNS jobs have finished
[2024-10-16 10:53:41,602 __init__ INFO] [mdscoring] Saving output to mdscoring.tsv
[2024-10-16 10:53:41,614 libutil ERROR] [Errno 2] No such file or directory: 'mdscoring_1.pdb'
Traceback (most recent call last):
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/modules/scoring/mdscoring/__init__.py", line 103, in _run
    self.per_interface_output(output_fname)
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/modules/scoring/__init__.py", line 69, in per_interface_output
    interfaces_scores = self.read_per_intreface_scores(pdb)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/anaconda3/lib/python3.12/site-packages/haddock/modules/scoring/__init__.py", line 140, in read_per_intreface_scores
    with open(pdb.file_name, 'r') as filin:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'mdscoring_1.pdb'
[2024-10-16 10:53:41,618 libutil ERROR] [Errno 2] No such file or directory: 'mdscoring_1.pdb'
[2024-10-16 10:53:41,618 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-10-16 10:53:41,618 libutil INFO] Finished at 16/10/2024 10:53:41. For any help contact us at https://github.com/haddocking/haddock3/issues. La revedere! Dovidenia! Tchau!.
```
### `mdscoring-test.cfg` Configuration

The content of the `mdscoring-test.cfg` file used for the run:

```ini
run_dir = "/mnt/steven/program/haddock3/test_mdrun"

# execution mode
ncores = 40
mode = "local"

# ensemble of different complexes to be scored
molecules = [
    "/mnt/steven/program/Rosetta/Alphafold3_result/gen1.pdb",
    "/mnt/steven/program/Rosetta/Alphafold3_result/Pos1.pdb",
    "/mnt/steven/program/Rosetta/Alphafold3_result/ran1.pdb",
    "/mnt/steven/program/Rosetta/Alphafold3_result/p35637_gen.pdb",
    "/mnt/steven/program/Rosetta/Alphafold3_result/p35637_pos.pdb",
    "/mnt/steven/program/Rosetta/Alphafold3_result/p35647_ran1.pdb"
]

# ====================================================================
# Parameters for each stage are defined below

[topoaa]

[mdscoring]
tolerance = 20
contactairs = true
ssdihed = "alphabeta"
dnarest_on = true
per_interface_scoring = true

[caprieval]

**Comment by jkurpost** [comment]
You're welcome
[log.txt](https://github.com/user-attachments/files/17395804/log.txt)

**Comment by mgiulini** [comment]
Hi @jkurpost , could you please show us the content of `mdscoring.tsv` file (it should be in `run-dir/1_mdscoring`)? there is probably a problem in at least one of your input PDB files..it would be great if you could also upload them here as a zip

**Comment by jkurpost** [comment]
ok，thanks everyone

**Comment by rvhonorato** [comment]
follow-up: #1105
