### ISSUE TITLE
[rigidbody] fails on a custom input due to CNS errors

### ISSUE THREAD

**Issue by edikedik** [haddocking/haddock3#1135]
## **Module/Workflow/Library affected**

I started from an antibody-antigen example workflow [from the docs](https://www.bonvinlab.org/haddock3/_downloads/def03e5a2e87727569244cb5cc84651b/docking-antibody-antigen-CDR-accessible-full.cfg). Input structures are both regular proteins without any HETATM entries. The antibody was modeled by the AbodyBuilder2. I checked that both inputs pass `pdb_validate` format checks from the `pdb-tools`. The antigen was derived from a PDB X-ray structure.
After experimenting I arrived at the following configuration sufficient to reproduce the bug:

```
# directory 
run_dir = "run"

# compute mode
mode = "mpi"
ncores = 24
clean = true
debug = true

# molecules to be docked
molecules =  [
    "VH1.0.pdb",
    "P.pdb"
    ]

[topoaa]

[rigidbody]
tolerance = 5
sampling = 50
```

## **Expected behavior**

...

## **Actual behavior**

I'm getting an error on the [rigidbody] stage:

```
[2024-11-07 15:37:48,817 cli INFO]
##############################################
#                                            #
#                 HADDOCK3                   #
#                                            #
##############################################

!! Some of the HADDOCK3 components use CNS (Crystallographic and NMR System) which is free of use for non-profit applications. !!
!! For commercial use it is your own responsibility to have a proper license. !!
!! For details refer to the DISCLAIMER file in the HADDOCK3 repository. !!

Starting HADDOCK3 v2024.10.0b6 on 2024-11-07 15:37:00

Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]

[2024-11-07 15:37:50,704 libworkflow INFO] Reading instructions step 0_topoaa
[2024-11-07 15:37:50,704 libworkflow INFO] Reading instructions step 1_rigidbody
[2024-11-07 15:37:50,719 base_cns_module INFO] Running [topoaa] module
[2024-11-07 15:37:50,719 __init__ INFO] [topoaa] Molecule 1: VH1.0.pdb
[2024-11-07 15:37:50,720 __init__ INFO] [topoaa] Sanitizing molecule VH1.0.pdb
[2024-11-07 15:37:50,724 __init__ INFO] [topoaa] Topology CNS input created
[2024-11-07 15:37:50,724 __init__ INFO] [topoaa] Molecule 2: P.pdb
[2024-11-07 15:37:50,729 __init__ INFO] [topoaa] Sanitizing molecule P.pdb
[2024-11-07 15:37:50,746 __init__ INFO] [topoaa] Topology CNS input created
[2024-11-07 15:37:50,746 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2024-11-07 15:37:50,746 libmpi INFO] Executing tasks with the haddock3-mpitask runner using 24 processors...
[2024-11-07 15:38:00,713 __init__ INFO] [topoaa] CNS jobs have finished
[2024-11-07 15:38:00,715 base_cns_module INFO] Module [topoaa] finished.
[2024-11-07 15:38:00,715 __init__ INFO] [topoaa] took 10 seconds
[2024-11-07 15:38:01,615 base_cns_module INFO] Running [rigidbody] module
[2024-11-07 15:38:01,616 __init__ INFO] [rigidbody] crossdock=true
[2024-11-07 15:38:01,616 __init__ INFO] [rigidbody] Preparing jobs...
[2024-11-07 15:38:01,986 __init__ INFO] [rigidbody] Preparation took 0.369958 seconds
[2024-11-07 15:38:01,988 __init__ INFO] [rigidbody] Running CNS Jobs n=50
[2024-11-07 15:38:01,988 libmpi INFO] Executing tasks with the haddock3-mpitask runner using 24 processors...
[2024-11-07 15:38:04,354 __init__ INFO] [rigidbody] CNS jobs have finished
[2024-11-07 15:38:04,366 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 5.00%.
Traceback (most recent call last):
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/modules/sampling/rigidbody/__init__.py", line 248, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/modules/__init__.py", line 309, in export_io_models
    self.finish_with_error(_msg)
  File "/home/edik/mambaforge/envs/haddock3/lib/python3.12/site-packages/haddock/modules/__init__.py", line 317, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 5.00%.
[2024-11-07 15:38:04,368 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 5.00%.
[2024-11-07 15:38:04,368 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-11-07 15:38:04,368 libutil INFO] Finished at 07/11/2024 15:38:04. For any help contact us at https://github.com/haddocking/haddock3/issues. Good bye! Do pobachennya! Adiós!.
```

Upon inspecting the output, the issue is probably in the following recurring CNS error:

```
 %NEXTCD-ERR: Symbol not found:
             if ($mol_fix_origin_$maxid
                 ^^^^^^^^^^^^^^^^^^^^^^
 %PARSER error encountered: Encountered too many parsing errors.
   (CNS is in mode: SET ABORT=NORMal END)
```

For the full output example, please see the attached files below.

## **Steps to reproduce the behavior**

Please use the protocol and input files attached below.
`haddock3 protocol.cfg` 

## **Version**

`2024.10.0b6`

## **Additional context**

[Inputs.zip](https://github.com/user-attachments/files/17664330/Inputs.zip)

[1_rigidbody.zip](https://github.com/user-attachments/files/17664408/1_rigidbody.zip)

---

Looking forward to any assistance!

Cheers,
Ivan

**Comment by amjjbonvin** [comment]
Did you try running this in local mode instead of mpi? 
MPI does anyway not make sense if you are running within the same system/node

Could be there is an issue with your MPI installation.

**Comment by edikedik** [comment]
You're right, it doesn't :)

Tried now - same outcome.

**Comment by amjjbonvin** [comment]
And you two starting molecules are different chainIDs?

Can you check the content of the rigidbody directory? Any out file? 
If not, rerun, but defining `debug=true` in the header of the config file.

**Comment by edikedik** [comment]
> And you two starting molecules are different chainIDs?
Yes, A for an antigen, HL for an antibody.

> Can you check the content of the rigidbody directory? Any out file?
Yes, there are output files for each of the 50 samples requested. I've attached outputs for one sample (obtained with debug mode turned on) to the initial message above.

**Comment by edikedik** [comment]
Indeed, that was the issue. Thanks for your time!
