### ISSUE TITLE
No such file or directory: 'sbatch'

### ISSUE THREAD

**Issue by bestz123** [haddocking/haddock3#1165]
## **Question**

When I run this script
haddock3 docking-protein-peptide-full.cfg, the code has the following error

## **Code snippet**

```text
[2024-12-01 18:57:46,976 cli INFO] 
##############################################
#                                            #
#                 HADDOCK3                   #
#                                            #
##############################################

!! Some of the HADDOCK3 components use CNS (Crystallographic and NMR System) which is free of use for non-profit applications. !!
!! For commercial use it is your own responsibility to have a proper license. !!
!! For details refer to the DISCLAIMER file in the HADDOCK3 repository. !!

Starting HADDOCK3 v2024.10.0b7 on 2024-12-01 18:57:00

Python 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:27:36) [GCC 13.3.0]

[2024-12-01 18:57:51,095 libworkflow INFO] Reading instructions step 0_topoaa
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 1_rigidbody
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 2_caprieval
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 3_seletop
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 4_flexref
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 5_caprieval
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 6_emref
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 7_caprieval
[2024-12-01 18:57:51,096 libworkflow INFO] Reading instructions step 8_clustfcc
[2024-12-01 18:57:51,097 libworkflow INFO] Reading instructions step 9_seletopclusts
[2024-12-01 18:57:51,097 libworkflow INFO] Reading instructions step 10_caprieval
[2024-12-01 18:57:51,097 libworkflow INFO] Reading instructions step 11_caprieval
[2024-12-01 18:57:51,111 base_cns_module INFO] Running [topoaa] module
[2024-12-01 18:57:51,111 __init__ INFO] [topoaa] Molecule 1: 1NX1_protein.pdb
[2024-12-01 18:57:51,112 __init__ INFO] [topoaa] Sanitizing molecule 1NX1_protein.pdb
[2024-12-01 18:57:51,117 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-01 18:57:51,117 __init__ INFO] [topoaa] Molecule 2: DAIDALSSDFT_3conformations.pdb
[2024-12-01 18:57:51,117 __init__ INFO] [topoaa] Sanitizing molecule DAIDALSSDFT_3conformations_1.pdb
[2024-12-01 18:57:51,118 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-01 18:57:51,118 __init__ INFO] [topoaa] Sanitizing molecule DAIDALSSDFT_3conformations_2.pdb
[2024-12-01 18:57:51,119 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-01 18:57:51,119 __init__ INFO] [topoaa] Sanitizing molecule DAIDALSSDFT_3conformations_3.pdb
[2024-12-01 18:57:51,120 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-01 18:57:51,120 __init__ INFO] [topoaa] Running CNS Jobs n=4
[2024-12-01 18:57:51,120 libhpc INFO] Concatenating, each .job will produce 5 (or less) models
[2024-12-01 18:57:51,120 libhpc INFO] > Running batch 1/1
[2024-12-01 18:57:51,122 libutil ERROR] [Errno 2] No such file or directory: 'sbatch'
Traceback (most recent call last):
  File "/mnt/zyz/work/github/hdock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/mnt/zyz/work/github/hdock3/src/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "/mnt/zyz/work/github/hdock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/mnt/zyz/work/github/hdock3/src/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "/mnt/zyz/work/github/hdock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/mnt/zyz/work/github/hdock3/src/haddock/modules/topology/topoaa/__init__.py", line 279, in _run
    engine.run()
  File "/mnt/zyz/work/github/hdock3/src/haddock/libs/libhpc.py", line 180, in run
    worker.run()
  File "/mnt/zyz/work/github/hdock3/src/haddock/libs/libhpc.py", line 110, in run
    p = subprocess.run(shlex.split(cmd), capture_output=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/zyz/anaconda3/envs/haddock/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/zyz/anaconda3/envs/haddock/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/mnt/zyz/anaconda3/envs/haddock/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'
[2024-12-01 18:57:51,123 libutil ERROR] [Errno 2] No such file or directory: 'sbatch'
[2024-12-01 18:57:51,123 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-12-01 18:57:51,123 libutil INFO] Finished at 01/12/2024 18:57:51. For any help contact us at https://github.com/haddocking/haddock3/issues. Adiós! Agur! Tot ziens!.
```

**Comment by amjjbonvin** [comment]
You should change the running mode.
It looks like the sbatch command (part of slurm) is not found.

**Comment by zongmingchua** [comment]
> You should change the running mode. It looks like the sbatch command (part of slurm) is not found.

I encountered a similar issue! Could you elaborate on how the 'running mode' can be changed?

**Comment by amjjbonvin** [comment]
It is defined by the mode parameter in the workflow config file, e.g.:

# execution mode
mode = “local"
ncores = 50


This would run haddock3 locally where it is started and use a max of 50 cores (if available).

**Comment by VGPReys** [comment]
#### To add to Alex answer

Haddock3 has 3 running modes:
- **local**: that will use your computer resources
- **batch**: that will use the queuing system SLURM to send batches of jobs
- **mpi**: that will use OpenMPI to send jobs over multiple nodes

Note that both `batch` and `mpi` running modes are built to run on HPC infrastructures.
If you want to run it on you machine, it is better to use the `local` mode.

**Comment by bestz123** [comment]
> @bestz123更改执行模式后，您的问题解决了吗？

Yes, after I changed the running mode in the cfg format, the program ran successfully，Thank you very much.
