### ISSUE TITLE
haddock-2024.12.0b7 ::  examples failure

### ISSUE THREAD

**Issue by EricDeveaud** [haddocking/haddock3#1167]
Hello, 

I just installed haddock-2024.12.0b7 from release tag [archive](https://github.com/haddocking/haddock3/archive/refs/tags/2024.12.0b7.tar.gz) 

after checking some issues (eg #329) I recompiled cns_solve from `cns_solve_1.3_all.tar.gz` using the [CNS installation documentation](https://github.com/haddocking/haddock3/blob/main/docs/CNS.md#cns-installation).

tools used of build//installation 
```
python/3.10.7
gcc/12.3.0
```

cns starts smoothly. see:
```
build [rpm]:src/haddock3 > ./haddock3-2024.12.0b7/cns_solve_1.3/intel-x86_64bit-linux/source/cns_solve-2412051749.exe
          ============================================================
          |                                                          |
          |            Crystallography & NMR System (CNS)            |
          |                         CNSsolve                         |
          |                                                          |
          ============================================================
           Version: 1.3 at patch level U
           Status: Special UU release with Rg, paramagnetic
                   and Z-restraints (A. Bonvin, UU 2013)
          ============================================================
           Written by: A.T.Brunger, P.D.Adams, G.M.Clore, W.L.DeLano,
                       P.Gros, R.W.Grosse-Kunstleve,J.-S.Jiang,J.M.Krahn,
                       J.Kuszewski, M.Nilges, N.S.Pannu, R.J.Read,
                       L.M.Rice, G.F.Schroeder, T.Simonson, G.L.Warren.
           Copyright (c) 1997-2010 Yale University
          ============================================================
           Running on machine: hostname unknown (x86_64/Linux,64-bit)
           Program started by: gensoft
           Program started at: 18:03:50 on 05-Dec-2024
          ============================================================

 FFT3C: Using FFTPACK4.1

CNSsolve>
```

when I run the `run.py` from examples folder I have some "test" failure. in the form of `100.00% of output was not generated for this module and tolerance was set to XX.00%.`

see for example.

```
***************** DOCKING-ANTIBODY-ANTIGEN-RANAIRCDR-TEST.CFG ******************

[2024-12-05 17:51:12,422 cli INFO]
##############################################
#                                            #
#                 HADDOCK3                   #
#                                            #

SNIP//SNAP

[2024-12-05 17:51:59,941 libparallel INFO] Using 10 cores
[2024-12-05 17:52:00,145 libparallel INFO] 10 tasks finished
[2024-12-05 17:52:00,145 __init__ INFO] [flexref] CNS jobs have finished
[2024-12-05 17:52:00,152 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.
Traceback (most recent call last):
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/refinement/flexref/__init__.py", line 159, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/__init__.py", line 309, in export_io_models
    self.finish_with_error(_msg)
  File "/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/__init__.py", line 317, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 20.00%.
[2024-12-05 17:52:00,153 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.
[2024-12-05 17:52:00,153 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-12-05 17:52:00,154 libutil INFO] Finished at 05/12/2024 17:52:00. For any help contact us at https://github.com/haddocking/haddock3/issues. Do pobachennya! La revedere! Agur!.
```
DOCKING-FLEXREF-PROTEIN-GLYCAN-TEST.CFG

same apply to eg
```
DOCKING-ANTIBODY-ANTIGEN-RANAIRCDR-CLT-TEST.CFG
DOCKING-ANTIBODY-ANTIGEN-CDR-ACCESSIBLE-TEST.CFG
DOCKING-ANTIBODY-ANTIGEN-CDR-ACCESSIBLE-CLT-TEST.CFG
DOCKING-ANTIBODY-ANTIGEN-CDR-NMR-CSP-TEST.CFG
DOCKING-PROTEIN-DNA-TEST.CFG
DOCKING-PROTEIN-DNA-MDREF-TEST.CFG
DOCKING-PROTEIN-DNA-CMREST-TEST.CFG
DOCKING-PROTEIN-HOMOTRIMER-TEST.CFG
DOCKING-PROTEIN-GLYCAN-TEST.CFG
DOCKING-PROTEIN-GLYCAN-ILRMSD-TEST.CFG
DOCKING-FLEXREF-PROTEIN-GLYCAN-TEST.CFG
DOCKING-PROTEIN-LIGAND-SHAPE-TEST.CFG
DOCKING-PROTEIN-LIGAND-TEST.CFG
DOCKING-PROTEIN-PEPTIDE-TEST.CFG
DOCKING-PROTEIN-PEPTIDE-MDREF-TEST.CFG
DOCKING-PROTEIN-PROTEIN-TEST.CFG
DOCKING-PROTEIN-PROTEIN-CLTSEL-TEST.CFG
DOCKING-PROTEIN-PROTEIN-MDREF-TEST.CFG
DOCKING-MULTIPLE-TBLS-TEST.CFG
CYCLISE-PEPTIDE-TEST.CFG
MDSCORING-TEST.CFG

```
some examples succeed
```
DOCKING-EXIT-TEST.CFG
REFINE-COMPLEX-TEST.CFG
EMSCORING-TEST.CFG
EMSCORING-MDSCORING-TEST.CFG
TOPOAA-CAPRIEVAL-TEST.CFG
TOPOAA-ILRMSDMATRIX-CLUSTRMSD-TEST.CFG
ALASCAN-TEST.CFG
CONTMAP-TEST.CFG
```

output of `pip3 freeze`
```
/opt/gensoft/exe/haddock3/2024.12.0b7/venv/bin/pip3 pip3 freeze
biopython==1.84
freesasa==2.2.1
haddock3 @ file:///opt/gensoft/src/haddock3/haddock3-2024.12.0b7
jsonpickle==4.0.0
mpi4py==4.0.1
numpy==2.1.3
packaging==24.2
pandas==2.2.3
pdb-tools==2.5.0
plotly==5.24.1
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
scipy==1.14.1
six==1.17.0
tenacity==9.0.0
toml==0.10.2
tzdata==2024.2
```

what I'am doing wrong ? 

PS attcahed full run log
[haddock3.log.txt](https://github.com/user-attachments/files/18027366/haddock3.log.txt)
log

regards

Eric

**Comment by amjjbonvin** [comment]
How did you install it?

Could you try simply from the cloned GitHub repository:

	pip install .


Did you copy the cns executable into the haddock3-2024.12.0b7/bin directory (as simply cns)?

Did you follow the instructions for CNS from varia/cns1.3/README.md?

**Comment by mgiulini** [comment]
> > How did you install it?
> 
> python 3.10, virtulal env. pip install from release tag archive
> 
> > Could you try simply from the cloned GitHub repository:
> > pip install .
> 
> done and same behaviour....
> 
> > Did you copy the cns executable into the haddock3-2024.12.0b7/bin directory (as simply cns)?
> 
> yes.
> 
> > Did you follow the instructions for CNS from varia/cns1.3/README.md?
> 
> yes

Hi @EricDeveaud, I tried my best to reproduce your issue but didn't manage..there must be something wrong with your CNS executable.

I suggest you try to get the package simply from pypi
`pip install haddock3
`

Otherwise try deleting the repository folder and re-download it. After that running
`pip install .`should work.

If none of this works let me know!

**Comment by EricDeveaud** [comment]
pip install from pipy problem. with cns binary. 

see:
```
build [rpm]://tmp > /opt/gensoft/adm/Python/3.10/bin/python3.10 -m virtualenv haddock
created virtual environment CPython3.10.7.final.0-64 in 133ms
  creator CPython3Posix(dest=/tmp/haddock, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/gensoft/.local/share/virtualenv)
    added seed packages: pip==24.3.1, setuptools==75.3.0, wheel==0.44.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
build [rpm]://tmp > . haddock/bin/activate
(haddock) build [rpm]://tmp > pip install haddock3
Collecting haddock3
  Downloading haddock3-2024.10.0b7.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 177.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pdb-tools>=2.5.0 (from haddock3)
  Using cached pdb_tools-2.5.0-py3-none-any.whl.metadata (6.6 kB)
Collecting biopython==1.* (from haddock3)
  Using cached biopython-1.84-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting jsonpickle>=2.1.0 (from haddock3)
  Using cached jsonpickle-4.0.0-py3-none-any.whl.metadata (8.2 kB)
Collecting numpy==2.* (from haddock3)
  Using cached numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting pyyaml>=6.0 (from haddock3)
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting scipy>=1.10.0 (from haddock3)
  Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting toml>=0.10.2 (from haddock3)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting pandas==2.* (from haddock3)
  Using cached pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting plotly==5.24.1 (from haddock3)
  Using cached plotly-5.24.1-py3-none-any.whl.metadata (7.3 kB)
Collecting freesasa>=2.2.1 (from haddock3)
  Using cached freesasa-2.2.1-cp310-cp310-linux_x86_64.whl
Collecting python-dateutil>=2.8.2 (from pandas==2.*->haddock3)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.*->haddock3)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.*->haddock3)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting tenacity>=6.2.0 (from plotly==5.24.1->haddock3)
  Using cached tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting packaging (from plotly==5.24.1->haddock3)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.*->haddock3)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached biopython-1.84-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Using cached numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
Using cached pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Using cached plotly-5.24.1-py3-none-any.whl (19.1 MB)
Using cached jsonpickle-4.0.0-py3-none-any.whl (46 kB)
Using cached pdb_tools-2.5.0-py3-none-any.whl (207 kB)
Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tenacity-9.0.0-py3-none-any.whl (28 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: haddock3
  Building wheel for haddock3 (pyproject.toml) ... done
  Created wheel for haddock3: filename=haddock3-2024.10.0b7-cp310-cp310-linux_x86_64.whl size=4147885 sha256=80688b5beea69432593adfa138a60be89042fb88bb9afa751155cd7c4d17a681
  Stored in directory: /home/gensoft/.cache/pip/wheels/92/48/e9/41e84dbf2f23c57249c58b1e3beecf62e66f8a301ca22c5dee
Successfully built haddock3
Installing collected packages: pytz, pdb-tools, freesasa, tzdata, toml, tenacity, six, pyyaml, packaging, numpy, jsonpickle, scipy, python-dateutil, plotly, biopython, pandas, haddock3
Successfully installed biopython-1.84 freesasa-2.2.1 haddock3-2024.10.0b7 jsonpickle-4.0.0 numpy-2.1.3 packaging-24.2 pandas-2.2.3 pdb-tools-2.5.0 plotly-5.24.1 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 scipy-1.14.1 six-1.17.0 tenacity-9.0.0 toml-0.10.2 tzdata-2024.2
(haddock) build [rpm]://tmp > cd h
haddock/            hsperfdata_gensoft/
(haddock) build [rpm]://tmp > cd haddock/
(haddock) build [rpm]:tmp/haddock > find . -type f -name cns
./lib/python3.10/site-packages/haddock/bin/cns
(haddock) build [rpm]:tmp/haddock > ./lib/python3.10/site-packages/haddock/bin/cns
./lib/python3.10/site-packages/haddock/bin/cns: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./lib/python3.10/site-packages/haddock/bin/cns)
./lib/python3.10/site-packages/haddock/bin/cns: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./lib/python3.10/site-packages/haddock/bin/cns)
./lib/python3.10/site-packages/haddock/bin/cns: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./lib/python3.10/site-packages/haddock/bin/cns)
(haddock) build [rpm]:tmp/haddock >
```

thats the reason I rebuilt  cns, follwing instructions here: https://github.com/haddocking/haddock3/blob/main/docs/CNS.md

**Comment by EricDeveaud** [comment]
Hello, 

dunno if it may helps but I tarcked the flexref job, at least the first one. 
and isolated the following cns params file. 
let me know if it is correct (see bellow)

exported the following:
```
export MODULE=/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/refinement/flexref/cns   MODDIR=. TOPPAR=/opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/cns/toppar
```

the ran in `/opt/gensoft/src/haddock3/haddock3-2024.12.0b7/examples/docking-antibody-antigen/run1-ranairCDR-test/05_flexref`

`cat  cns.params.txt | /opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/bin/cns` 

and got the bellow attached error log.

[cns.params.txt](https://github.com/user-attachments/files/18038672/cns.params.txt)
[cns.erro.log.txt](https://github.com/user-attachments/files/18038675/cns.erro.log.txt)


NB  all file are readable and present.
see:
```
build [rpm]:haddock3/haddock3-2024.12.0b7 > ls /opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/refinement/flexref/cns/ -l
total 244
-rw-rw-r-- 1 gensoft gensoft  1116 Dec  6 08:09 calc_free-ene.cns
-rw-rw-r-- 1 gensoft gensoft  1736 Dec  6 08:09 check-homomers.cns
-rw-rw-r-- 1 gensoft gensoft  5043 Dec  6 08:09 cm-restraints.cns
-rw-rw-r-- 1 gensoft gensoft  1426 Dec  6 08:09 contactairs.cns
-rw-rw-r-- 1 gensoft gensoft  3912 Dec  6 08:09 covalions.cns
-rw-rw-r-- 1 gensoft gensoft  4071 Dec  6 08:09 def_solv_param.cns
-rw-rw-r-- 1 gensoft gensoft 19764 Dec  6 08:09 dna-rna_restraints.cns
-rw-rw-r-- 1 gensoft gensoft  1243 Dec  6 08:09 flex_segment.cns
-rw-rw-r-- 1 gensoft gensoft  2320 Dec  6 08:09 flex_segment_back.cns
-rw-rw-r-- 1 gensoft gensoft  2552 Dec  6 08:09 flex_segment_side.cns
-rw-rw-r-- 1 gensoft gensoft  1934 Dec  6 08:09 flexauto-neighbors.cns
-rw-rw-r-- 1 gensoft gensoft 17881 Dec  6 08:09 flexref.cns
-rw-rw-r-- 1 gensoft gensoft  3281 Dec  6 08:09 numtrees.cns
-rw-rw-r-- 1 gensoft gensoft 12552 Dec  6 08:09 print_coorheader.cns
-rw-rw-r-- 1 gensoft gensoft  4239 Dec  6 08:09 protein-ss-restraints-all.cns
-rw-rw-r-- 1 gensoft gensoft  6002 Dec  6 08:09 protein-ss-restraints-alpha-beta.cns
-rw-rw-r-- 1 gensoft gensoft  5163 Dec  6 08:09 protein-ss-restraints-alpha.cns
-rw-rw-r-- 1 gensoft gensoft  7800 Dec  6 08:09 random_rotations.cns
-rw-rw-r-- 1 gensoft gensoft  2026 Dec  6 08:09 read_data.cns
-rw-rw-r-- 1 gensoft gensoft  1817 Dec  6 08:09 read_noes.cns
-rw-rw-r-- 1 gensoft gensoft  2007 Dec  6 08:09 read_param.cns
-rw-rw-r-- 1 gensoft gensoft  5237 Dec  6 08:09 restrain-ions.cns
-rw-rw-r-- 1 gensoft gensoft  3809 Dec  6 08:09 sa_ltad_cool1.cns
-rw-rw-r-- 1 gensoft gensoft  3868 Dec  6 08:09 sa_ltad_cool2.cns
-rw-rw-r-- 1 gensoft gensoft  3867 Dec  6 08:09 sa_ltad_cool3.cns
-rw-rw-r-- 1 gensoft gensoft  1818 Dec  6 08:09 sa_ltad_hightemp.cns
-rw-rw-r-- 1 gensoft gensoft  2349 Dec  6 08:09 scale_inter.cns
-rw-rw-r-- 1 gensoft gensoft  1836 Dec  6 08:09 scale_inter_final.cns
-rw-rw-r-- 1 gensoft gensoft  2071 Dec  6 08:09 scale_inter_only.cns
-rw-rw-r-- 1 gensoft gensoft  1489 Dec  6 08:09 scale_intra_only.cns
-rw-rw-r-- 1 gensoft gensoft  9324 Dec  6 08:09 separate.cns
-rw-rw-r-- 1 gensoft gensoft   850 Dec  6 08:09 setflags.cns
-rw-rw-r-- 1 gensoft gensoft 32233 Dec  6 08:09 symmultimer.cns
-rw-rw-r-- 1 gensoft gensoft  4595 Dec  6 08:09 torsiontop.cns
```
hope we will find a solution

**Comment by EricDeveaud** [comment]
I check that all @MODULES from cns.params.txt are present 

build [rpm]:run1-ranairCDR-test/05_flexref > for p in `grep @MODULE log  | awk -F: '{print $2}' | sort | uniq`
> do
> ls /opt/gensoft/exe/haddock3/2024.12.0b7/venv/lib/python3.10/site-packages/haddock/modules/refinement/flexref/cns/$p > /dev/null
> done
build [rpm]:run1-ranairCDR-test/05_flexref > echo $?
0
```

**Comment by amjjbonvin** [comment]
Try then replacing the cns exec coming from pip in ./lib/python3.10/site-packages/haddock/bin/cns  by your compiled version

**Comment by amjjbonvin** [comment]
Importantly when compiling CNS did you first follow the instructions from the README.md file in varia/cns1.3 from the haddock3 directory? This will replace/add some files that have extended parameter settings (path length might be an issue)

**Comment by EricDeveaud** [comment]
`/lib/python3.10/site-packages/haddock/bin/cns` is already the home compiled one.

> did you first follow the instructions from the README.md file in varia/cns1.3

I think yes ;-)
I've built cns som many times, using various compilers gcc version, starting build from scratch each time

here's my build rule for cns

```
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7 && rm cns_solve_1.3 
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7 && tar xf cns_solve_1.3_all.tar.gz
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7/cns_solve_1.3 && sed -i -e 's|_CNSsolve_location_|'"$PWD"'|' cns_solve_env
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7 && cp -r varia/cns1.3/[bis]*  cns_solve_1.3/
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7/cns_solve_1.3 && sed -i -e 's|\tlex |\tflex |' instlib/utils/Makefile
cd /opt/gensoft/src/haddock3/haddock3-2024.12.0b7/cns_solve_1.3 && . /opt/gensoft/adm/etc/profile.d/modules.sh && module purge && AUTOLOADMODULE=1 module load  gcc/11.3.0  flex \
                     && make install compiler=gfortran
```

**Comment by amjjbonvin** [comment]
I found the problem. We forgot to update `cns.inc` in the source directory. Edit it in your CNS installation, change the following line:

```
PARAMETER (WORD_SIZE=160)
```

to 
```
PARAMETER (WORD_SIZE=264)
```

Recompile and replace the exec.

**Comment by EricDeveaud** [comment]
currently building

stay tunned ;-)

**Comment by amjjbonvin** [comment]
PS: Another solution to this path problem should be to define in the workflow config file:

```
self_contained = true
```

But better to have a recompiled CNS

**Comment by EricDeveaud** [comment]
new cns built with WORD_SIZE=264, no luck

see:
```
[2024-12-06 15:46:42,837 __init__ INFO] [flexref] CNS jobs have finished
[2024-12-06 15:46:42,844 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%
```

**Comment by EricDeveaud** [comment]
OK see: This option will copy the CNS scripts and executable to the run folder.

hummmm makes me think to a problen of path length. sorry, not fluent enough in fortran to dive in cns code // cns patches

**Comment by mgiulini** [comment]
indeed a problem with the path length accepted by your executable..if you add `self_contained` to any workflow you want to run you should be fine.

**Comment by EricDeveaud** [comment]
Hummm. I would prefer to find the culprit to avoid this necessity.
I will try to check the fortran code. 

in the mean time I guess I can turn self_contained=true for all the users on the cluster by settting `self_contained` to true in `src/haddock/modules/defaults.yaml` 
is this right ?

**Comment by mknotts623** [comment]
I've also been having this problem for protein small molecule docking (although curiously the .psf is made for the protein, just not the ligand, so I'm getting 50% output not generated). I added self_contained=true to my .cfg but now it fails before running topoaa, with a ModuleNotFound error for the clis. Tried a fresh conda environment and install but i'm getting the same error.

**Comment by amjjbonvin** [comment]
Yes - that should do.

And the current word length is already max if you indeed modified cns.inc as indicated and copied the CNS exec to the proper location.

There is yet one another thing to try: install haddock3 in development mode. In doing that the files will be located under the build directly on the haddock3 location and might have a shorter path (assuming the path is the issue). For this do:

pip install -e '.[dev,docs]'

**Comment by amjjbonvin** [comment]
Are you running the default ligand example?

If docking another system, you will have to create and provide the ligand topo/param files.

**Comment by EricDeveaud** [comment]
Hello.

finally abble to sort this path length problem.

modification are quite simple, thus I won't create a PR for this

1) as already mentionned change `cns.inc` from `PARAMETER (WORD_SIZE=160)`  to `PARAMETER (WORD_SIZE=264)`

2) patch `machine_f.f`
```
--- varia/cns1.3/instlib/machine/supported/intel-x86_64bit-linux/machine_f.f.ori
+++ varia/cns1.3/instlib/machine/supported/intel-x86_64bit-linux/machine_f.f
@ -292,7 +292,7 @@ C input/output
       CHARACTER*(*) FILE, FORM, ACCESS
       LOGICAL ERR
 C local
-      CHARACTER*132  LSTFIL, NEWFIL
+      CHARACTER*264  LSTFIL, NEWFIL
       INTEGER I, FILLEN
       LOGICAL EXISTS
 C begin
@@ -584,7 +584,7 @@ C I/O
       INTEGER WDLEN, WDMAX
 C local
       INTEGER L, LL, LLL, MXPATH
-      PARAMETER (MXPATH=132)
+      PARAMETER (MXPATH=264)
       CHARACTER*(MXPATH) PATH, TEMP
       LOGICAL GOTIT
 C begin
@@ -827,7 +827,7 @@ C
       CHARACTER*(*) STRING
 C
       INTEGER MXPATH
-      PARAMETER (MXPATH=132)
+      PARAMETER (MXPATH=264)
       CHARACTER*(MXPATH) PATH
       INTEGER IUNIT, STLEN
       CHARACTER*(COMMAX) LINE
```

3) copy from original cns_solve `source/comand.inc` to `varia/cns1.3/source/comand.inc` and change all occurences of 
`CHARACTER*132` to `CHARACTER*264`


regards

Eric

**Comment by rvhonorato** [comment]
Thanks for the time @EricDeveaud, with your suggestion we can hopefully implement a proper fix instead of the previously proposed workarounds 🚀
