### ISSUE TITLE
'NoneType' object has no attribute 'identificator'

### ISSUE THREAD

**Issue by Harshilwalia777** [haddocking/haddock3#1181]
```
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

[2024-12-11 22:37:53,952 libworkflow INFO] Reading instructions step 0_topoaa
[2024-12-11 22:37:53,952 libworkflow INFO] Reading instructions step 1_rigidbody
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 2_caprieval
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 3_seletop
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 4_caprieval
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 5_flexref
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 6_caprieval
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 7_emref
[2024-12-11 22:37:53,953 libworkflow INFO] Reading instructions step 8_caprieval
[2024-12-11 22:37:53,954 libworkflow INFO] Reading instructions step 9_clustfcc
[2024-12-11 22:37:53,954 libworkflow INFO] Reading instructions step 10_seletopclusts
[2024-12-11 22:37:53,954 libworkflow INFO] Reading instructions step 11_caprieval
[2024-12-11 22:37:53,968 base_cns_module INFO] Running [topoaa] module
[2024-12-11 22:37:53,968 __init__ INFO] [topoaa] Molecule 1: cro.pdb
[2024-12-11 22:37:53,969 __init__ INFO] [topoaa] Sanitizing molecule cro.pdb
[2024-12-11 22:37:53,971 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-11 22:37:53,971 __init__ INFO] [topoaa] Molecule 2: dna.pdb
[2024-12-11 22:37:53,971 __init__ INFO] [topoaa] Sanitizing molecule dna.pdb
[2024-12-11 22:37:53,973 __init__ INFO] [topoaa] Topology CNS input created
[2024-12-11 22:37:53,973 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2024-12-11 22:37:53,973 libutil INFO] Selected 2 cores to process 2 jobs, with 16 maximum available cores.
[2024-12-11 22:37:53,978 libparallel INFO] Using 2 cores
[2024-12-11 22:37:54,365 libparallel INFO] 2 tasks finished
[2024-12-11 22:37:54,365 __init__ INFO] [topoaa] CNS jobs have finished
[2024-12-11 22:37:54,366 base_cns_module INFO] Module [topoaa] finished.
[2024-12-11 22:37:54,366 __init__ INFO] [topoaa] took 0 seconds
[2024-12-11 22:37:54,705 base_cns_module INFO] Running [rigidbody] module
[2024-12-11 22:37:54,706 __init__ INFO] [rigidbody] crossdock=true
[2024-12-11 22:37:54,706 __init__ INFO] [rigidbody] Preparing jobs...
[2024-12-11 22:37:54,706 libutil INFO] Selected 8 cores to process 10 jobs, with 16 maximum available cores.
[2024-12-11 22:37:54,706 libparallel INFO] Using 8 cores
[2024-12-11 22:37:54,719 libparallel INFO] 10 tasks finished
[2024-12-11 22:37:54,720 __init__ INFO] [rigidbody] Preparation took 0.013562 seconds
[2024-12-11 22:37:54,720 __init__ INFO] [rigidbody] Running CNS Jobs n=10
[2024-12-11 22:37:54,720 libutil INFO] Selected 8 cores to process 10 jobs, with 16 maximum available cores.
[2024-12-11 22:37:54,720 libparallel INFO] Using 8 cores
[2024-12-11 22:37:58,938 libparallel INFO] 10 tasks finished
[2024-12-11 22:37:58,938 __init__ INFO] [rigidbody] CNS jobs have finished
[2024-12-11 22:37:58,941 base_cns_module INFO] Module [rigidbody] finished.
[2024-12-11 22:37:58,942 __init__ INFO] [rigidbody] took 4 seconds
[2024-12-11 22:37:58,956 __init__ INFO] Running [caprieval] module
[2024-12-11 22:37:58,956 capri INFO] Found previous CNS step: 01_rigidbody
[2024-12-11 22:37:59,108 capri INFO] Saved scoring weights to: weights_params.json
[2024-12-11 22:37:59,117 libutil INFO] Selected 8 cores to process 10 jobs, with 16 maximum available cores.
[2024-12-11 22:37:59,117 libparallel INFO] Using 8 cores
[2024-12-11 22:37:59,142 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,142 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,142 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,142 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,142 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,148 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,148 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,150 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,150 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,151 libparallel WARNING] Exception in task execution: maximum recursion depth exceeded
[2024-12-11 22:37:59,153 libparallel INFO] 10 tasks finished
[2024-12-11 22:37:59,154 libutil ERROR] 'NoneType' object has no attribute 'identificator'
Traceback (most recent call last):
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/modules/__init__.py", line 245, in run
    self._run()
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/modules/analysis/caprieval/__init__.py", line 131, in _run
    jobs = sorted(jobs, key=lambda capri: capri.identificator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/root777/anaconda3/envs/haddock/lib/python3.12/site-packages/haddock/modules/analysis/caprieval/__init__.py", line 131, in <lambda>
    jobs = sorted(jobs, key=lambda capri: capri.identificator)
                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'identificator'
[2024-12-11 22:37:59,157 libutil ERROR] 'NoneType' object has no attribute 'identificator'
[2024-12-11 22:37:59,157 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-12-11 22:37:59,157 libutil INFO] Finished at 11/12/2024 22:37:59. For any help contact us at https://github.com/haddocking/haddock3/issues. Tchau! Do pobachennya! Até logo!. 
```

**Comment by Harshilwalia777** [comment]
how to resolve it, pls help

**Comment by mgiulini** [comment]
hi @Harshilwalia777 , are you running the most recent version of the code? if that is the case, please provide us the used workflow and the input files.
otherwise, please update the software via mypi (`pip install haddock3`) or according to these instructions https://github.com/haddocking/haddock3/blob/main/docs/INSTALL.md and try again

**Comment by Harshilwalia777** [comment]
i have used latest

**Comment by Harshilwalia777** [comment]
I am using latest haddock 3 by using pip Install Haddock 3. Test it again
by reinstalling it in another environment using conda.

**Comment by amjjbonvin** [comment]
Please provide the output of the git command I gave in my previous message? Is it the same I provided?

If not, rather try in your conda environment the following installation procedure:

```
git clone https://github.com/haddocking/haddock3.git
cd haddock3
pip install .
```

**Comment by Harshilwalia777** [comment]
[2024-12-12 16:40:45,738 contmap INFO] Generated report file:
ContactMapReport.html
[2024-12-12 16:40:45,743 __init__ INFO] Module [contactmap] finished.
[2024-12-12 16:40:45,743 __init__ INFO] [contactmap] took 0 seconds
[2024-12-12 16:40:45,743 cli_analyse INFO] Running haddock3-analyse on ./,
modules [], with top_cluster = 10
[2024-12-12 16:40:45,754 cli_analyse INFO] Created directory:
/home/root777/haddock3/examples/analysis/test_contmap/analysis
[2024-12-12 16:40:45,754 cli_analyse INFO] Reading input run directory
[2024-12-12 16:40:45,754 cli_analyse INFO] selected steps: 0_topoaa,
1_rigidbody, 2_clustfcc, 3_contactmap
[2024-12-12 16:40:45,754 cli_analyse INFO] Analysing step 0_topoaa
[2024-12-12 16:40:45,755 cli_analyse WARNING] Could not execute the
analysis for step 0_topoaa. The following error occurred 'dict' object has
no attribute 'rel_path'
[2024-12-12 16:40:45,755 cli_analyse INFO] Analysing step 1_rigidbody
[2024-12-12 16:40:45,757 cli_unpack INFO] Unpacking '../1_rigidbody' folder
[2024-12-12 16:40:45,758 libtimer INFO] unpacking took 0 seconds
[2024-12-12 16:40:45,788 capri INFO] Found previous CNS step: 1_rigidbody
[2024-12-12 16:40:46,088 capri INFO] Saved scoring weights to:
weights_params.json
[2024-12-12 16:40:46,088 __init__ INFO] [caprieval] No reference was given.
Using the structure with the lowest score from previous step
[2024-12-12 16:40:46,210 libutil INFO] Selected 5 cores to process 20 jobs,
with 16 maximum available cores.
[2024-12-12 16:40:46,211 libparallel INFO] Using 5 cores
[2024-12-12 16:40:46,262 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,262 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,263 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,265 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,270 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,288 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,290 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,292 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,292 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,296 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,313 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,315 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,316 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,316 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,321 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,336 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,339 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,342 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,342 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,344 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,347 libparallel INFO] 20 tasks finished
[2024-12-12 16:40:46,348 cli_analyse WARNING] Could not execute the
analysis for step 1_rigidbody. The following error occurred 'NoneType'
object has no attribute 'identificator'
[2024-12-12 16:40:46,348 cli_analyse INFO] Analysing step 2_clustfcc
[2024-12-12 16:40:46,350 cli_unpack INFO] Unpacking '../1_rigidbody' folder
[2024-12-12 16:40:46,351 libtimer INFO] unpacking took 0 seconds
[2024-12-12 16:40:46,373 capri INFO] Found previous CNS step: 1_rigidbody
[2024-12-12 16:40:46,646 capri INFO] Saved scoring weights to:
weights_params.json
[2024-12-12 16:40:46,646 __init__ INFO] [caprieval] No reference was given.
Using the structure with the lowest score from previous step
[2024-12-12 16:40:46,744 libutil INFO] Selected 5 cores to process 17 jobs,
with 16 maximum available cores.
[2024-12-12 16:40:46,745 libparallel INFO] Using 5 cores
[2024-12-12 16:40:46,792 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,795 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,801 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,801 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,804 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,815 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,818 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,826 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,830 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,839 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,842 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,849 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,854 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,861 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,865 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,870 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,879 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:46,882 libparallel INFO] 17 tasks finished
[2024-12-12 16:40:46,883 cli_analyse WARNING] Could not execute the
analysis for step 2_clustfcc. The following error occurred 'NoneType'
object has no attribute 'identificator'
[2024-12-12 16:40:46,883 cli_analyse INFO] Analysing step 3_contactmap
[2024-12-12 16:40:46,885 cli_unpack INFO] Unpacking '../1_rigidbody' folder
[2024-12-12 16:40:46,886 libtimer INFO] unpacking took 0 seconds
[2024-12-12 16:40:46,907 capri INFO] Found previous CNS step: 1_rigidbody
[2024-12-12 16:40:47,177 capri INFO] Saved scoring weights to:
weights_params.json
[2024-12-12 16:40:47,177 __init__ INFO] [caprieval] No reference was given.
Using the structure with the lowest score from previous step
[2024-12-12 16:40:47,272 libutil INFO] Selected 5 cores to process 17 jobs,
with 16 maximum available cores.
[2024-12-12 16:40:47,273 libparallel INFO] Using 5 cores
[2024-12-12 16:40:47,314 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,319 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,323 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,326 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,329 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,339 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,342 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,346 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,351 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,362 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,365 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,368 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,374 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,384 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,387 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,391 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,397 libparallel WARNING] Exception in task execution:
maximum recursion depth exceeded
[2024-12-12 16:40:47,401 libparallel INFO] 17 tasks finished
[2024-12-12 16:40:47,401 cli_analyse WARNING] Could not execute the
analysis for step 3_contactmap. The following error occurred 'NoneType'
object has no attribute 'identificator'
[2024-12-12 16:40:47,401 cli_analyse INFO] cancelling unsuccesful analysis
folders
[2024-12-12 16:40:47,402 cli_traceback INFO] Running haddock3-traceback on
./
[2024-12-12 16:40:47,402 cli_traceback INFO] Reading input run directory
[2024-12-12 16:40:47,402 cli_traceback INFO] All_steps: 0_topoaa,
1_rigidbody, 2_clustfcc, 3_contactmap
[2024-12-12 16:40:47,403 cli_traceback INFO] Modules not to be analysed:
0_topoaa, 2_clustfcc, 3_contactmap
[2024-12-12 16:40:47,403 cli_traceback INFO] Steps to trace back:
1_rigidbody
[2024-12-12 16:40:47,403 cli_traceback INFO] Created directory:
/home/root777/haddock3/examples/analysis/test_contmap/traceback
[2024-12-12 16:40:47,403 cli_traceback INFO] Tracing back step 1_rigidbody
[2024-12-12 16:40:47,408 libworkflow WARNING] Error running traceback:
Cannot convert numpy.ndarray to numpy.ndarray
[2024-12-12 16:40:47,408 clean_steps INFO] Cleaning output for '0_topoaa'
using 5 cores.
[2024-12-12 16:40:47,573 libtimer INFO] cleaning output files took 0 seconds
[2024-12-12 16:40:47,573 clean_steps INFO] Cleaning output for
'1_rigidbody' using 5 cores.
[2024-12-12 16:40:47,988 libtimer INFO] cleaning output files took 0 seconds
[2024-12-12 16:40:47,989 clean_steps INFO] Cleaning output for '2_clustfcc'
using 5 cores.
[2024-12-12 16:40:48,023 libtimer INFO] cleaning output files took 0 seconds
[2024-12-12 16:40:48,023 clean_steps INFO] Cleaning output for
'3_contactmap' using 5 cores.
[2024-12-12 16:40:48,034 libtimer INFO] cleaning output files took 0 seconds
[2024-12-12 16:40:48,035 cli INFO] This HADDOCK3 run took: 54 seconds
[2024-12-12 16:40:48,035 greetings INFO] Your feedback matters in Haddock3!
Share your experience and help us grow:
[2024-12-12 16:40:48,035 greetings INFO] GitHub issues:
https://github.com/haddocking/haddock3/issues
[2024-12-12 16:40:48,035 greetings INFO] BioExcel feedback:
https://www.bonvinlab.org/feedback
[2024-12-12 16:40:48,035 greetings INFO] BioExcel forum:
https://ask.bioexcel.eu/c/haddock/6
[2024-12-12 16:40:48,035 cli INFO] Finished at 12/12/2024 16:40:48. Tot
ziens! Dovidenia! 再见!

**Comment by Harshilwalia777** [comment]
same result after reinstalling it.

**Comment by Harshilwalia777** [comment]
run analysis file 'contactmap.cfg' for checking haddock3

**Comment by amjjbonvin** [comment]
And you are running the default test example, no modifications?

On what hardware / operating system are you running?

We can not reproduce this problem.

**Comment by rvhonorato** [comment]
Hi @Harshilwalia777 - could you please follow this commands and provide me with the log?

Do this using pure python, not using anaconda.

```
git clone --depth 1 https://github.com/haddocking/haddock3
cd haddock3
python -m venv .venv
source .venv/bin/activate
cd haddock3/examples
haddock3 docking-protein-protein-test.cfg > log.txt
```

Please post here the text inside this `log.txt`
