### ISSUE TITLE
Scoring module broken

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#198]
I just added a new branch called `scoring-new` which contains the updated emscoring module and a new scoring example.

Currently, while the first stage (topoaa) is working fine, the `emscoring` module fails with the following error:
```
[2021-12-13 16:04:07,909 __init__ INFO] Running [emscoring] module
Traceback (most recent call last):
  File "/Users/abonvin/miniconda3/envs/haddock3/bin/haddock3", line 33, in <module>
    sys.exit(load_entry_point('haddock3', 'console_scripts', 'haddock3')())
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/clis/cli.py", line 67, in maincli
    cli(ap, main)
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/clis/cli.py", line 62, in cli
    main(**vars(cmd))
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/clis/cli.py", line 143, in main
    workflow.run()
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/libs/libworkflow.py", line 29, in run
    step.execute()
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/libs/libworkflow.py", line 114, in execute
    module.run(**self.config)
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/modules/__init__.py", line 107, in run
    self._run()
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/modules/scoring/emscoring/__init__.py", line 74, in _run
    models_to_score = [
  File "/Users/abonvin/haddock_git/haddock3/src/haddock/modules/scoring/emscoring/__init__.py", line 77, in <listcomp>
    if p.file_type == Format.PDB
AttributeError: 'dict' object has no attribute 'file_type'
```

Note that the new scoring example contains a variety of molecules and complex types, both single models and ensembles models.

**Comment by rvhonorato** [comment]
Closed with #199
