### ISSUE TITLE
Add support to mixed systems in `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#235]
So it can handle Protein-Ligand + Protein scenario and also proteins with modified residues.

**Comment by joaomcteixeira** [comment]
Was this closed by #230?

**Comment by rvhonorato** [comment]
> Was this closed by #230?

nope

**Comment by rvhonorato** [comment]
A bug related to the mixed system occurs when the reference has a modified residue not present in the models and can be seen in the `docking-protein-trimer` example

```
[2021-12-30 10:13:10,502 __init__ INFO] [caprieval]  cutoff: 10.0A
Traceback (most recent call last):
  File "/Users/rodrigo/anaconda3/envs/haddock3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/rodrigo/anaconda3/envs/haddock3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/rodrigo/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/rodrigo/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/rodrigo/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/rodrigo/anaconda3/envs/haddock3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/rodrigo/anaconda3/envs/haddock3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/rodrigo/anaconda3/envs/haddock3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/rodrigo/repos/haddock3/src/haddock/clis/cli.py", line 154, in <module>
    sys.exit(maincli())
  File "/Users/rodrigo/repos/haddock3/src/haddock/clis/cli.py", line 67, in maincli
    cli(ap, main)
  File "/Users/rodrigo/repos/haddock3/src/haddock/clis/cli.py", line 62, in cli
    main(**vars(cmd))
  File "/Users/rodrigo/repos/haddock3/src/haddock/clis/cli.py", line 143, in main
    workflow.run()
  File "/Users/rodrigo/repos/haddock3/src/haddock/libs/libworkflow.py", line 30, in run
    step.execute()
  File "/Users/rodrigo/repos/haddock3/src/haddock/libs/libworkflow.py", line 119, in execute
    module.run(**self.config)
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/__init__.py", line 121, in run
    self._run()
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/analysis/caprieval/__init__.py", line 74, in _run
    capri.irmsd(cutoff=irmsd_cutoff)
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 116, in irmsd
    ref_coord_dic, _ = self.load_coords(
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 514, in load_coords
    if atom_name not in self.atoms[resname]:
KeyError: 'CSP'
```

**Comment by joaomcteixeira** [comment]
Okay. I am deactivated the `caprieval` module for that example to merge #219, meanwhile this is solved.
