### ISSUE TITLE
`caprieval` fails if models from previous step do not have scores

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#251]
While this is a strange scenario if the PDBs have no scores the following error occurs:

```
[2022-01-03 17:59:31,024 __init__ INFO] Running [caprieval] module
[2022-01-03 18:02:28,373 libutil ERROR] '<' not supported between instances of 'PDBFile' and 'PDBFile'
Traceback (most recent call last):
  File "/Users/rodrigo/repos/haddock3/src/haddock/libs/libutil.py", line 307, in log_error_and_exit
    yield
  File "/Users/rodrigo/repos/haddock3/src/haddock/clis/cli.py", line 148, in main
    workflow.run()
  File "/Users/rodrigo/repos/haddock3/src/haddock/libs/libworkflow.py", line 30, in run
    step.execute()
  File "/Users/rodrigo/repos/haddock3/src/haddock/libs/libworkflow.py", line 111, in execute
    module.run(**self.config)
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/__init__.py", line 119, in run
    self._run()
  File "/Users/rodrigo/repos/haddock3/src/haddock/modules/analysis/caprieval/__init__.py", line 38, in _run
    model_l.sort()
TypeError: '<' not supported between instances of 'PDBFile' and 'PDBFile'
```

A way to handle this is to try/except and select the first model instead.

**Comment by joaomcteixeira** [comment]
We need to implement a `__lt__` and `__eq__` to the `model` class.

**Comment by AnastasiiaDuchenko** [comment]
Is it the same/or related issue

`2024-07-09 17:33:44,807 libutil ERROR] 0.40% of output was not generated for this module and tolerance was set to 0.00%.
Traceback (most recent call last):
  File "/users/aduchenk/software2/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/users/aduchenk/software2/haddock3/src/haddock/clis/cli.py", line 187, in main
    workflow.run()
  File "/users/aduchenk/software2/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/users/aduchenk/software2/haddock3/src/haddock/libs/libworkflow.py", line 158, in execute
    self.module.run()  # type: ignore
  File "/users/aduchenk/software2/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/users/aduchenk/software2/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 159, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/users/aduchenk/software2/haddock3/src/haddock/modules/__init__.py", line 298, in export_io_models
    self.finish_with_error(_msg)
  File "/users/aduchenk/software2/haddock3/src/haddock/modules/__init__.py", line 307, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 0.40% of output was not generated for this module and tolerance was set to 0.00%.
[2024-07-09 17:33:44,811 libutil ERROR] 0.40% of output was not generated for this module and tolerance was set to 0.00%.`

**Comment by VGPReys** [comment]
I don't think this is related, but I can help you.

You must set a higher value to the `tolerance` parameter (e.g: `tolerance = 5`).
This error occurs when one or more model were not generated by the module.
In most situations, this is not an issue, as a crash of a forcefield in MD (usually due to interactomic clash) can happen. This is compensated by the number of sampling, therefore loosing one structure/complex is fine.

If you do not want to recompute everything until the module that crashed, you can run the following command `haddock3 <config_file.cfg> --restart <module_id>`, where module_id is the next module to be run after the one that crashed.

**Comment by AnastasiiaDuchenko** [comment]
I greatly appreciate it. Thank you so much.
