### ISSUE TITLE
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 0.00%.

### ISSUE THREAD

**Issue by LoganLHJ** [haddocking/haddock3#342]
**<log>**
[2022-03-01 14:56:28,445 __init__ INFO] [topoaa] CNS jobs have finished
[2022-03-01 14:56:28,450 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 0.00%.
Traceback (most recent call last):
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/libs/libutil.py", line 320, in log_error_and_exit
    yield
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/clis/cli.py", line 152, in main
    workflow.run()
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/libs/libworkflow.py", line 32, in run
    step.execute()
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/libs/libworkflow.py", line 106, in execute
    module.run(**self.config)
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/modules/base_cns_module.py", line 48, in run
    self._run()
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 206, in _run
    self.finish_with_error(_msg)
  File "/BiO/Share/Tool/haddock/haddock3/src/haddock/modules/__init__.py", line 186, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 0.00%.
[2022-03-01 14:56:28,452 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 0.00%.
[2022-03-01 14:56:28,452 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2022-03-01 14:56:28,452 libutil INFO] Finished at 01/03/2022 14:56:28. For any help contact us at https://github.com/haddocking/haddock3/issues. Adéu-siau! Tot ziens! Dovidenia!.

**<description>**
'haddock3/examples/docking-protein-protein$ haddock3 docking-protein-protein-test.cfg'. When I tried to run an example file, I got this error message. I've tried to find out the reason, but I couldn't. What should I do in this situation?!

**Comment by amjjbonvin** [comment]
Which version are you running?

And which example?

Remember haddock3 is in active development.

Also check the output files in the 00_topoaa dir of the run.
Most likely something is wrong with your CNS installation.

**Comment by LoganLHJ** [comment]
Thank you for your email, sir.

I'm running the new version of haddock3 now (haddock3 - 3.0.0)

And I run the example file mentioned in your USAGE.md file like

cd examples/docking-protein-protein

haddock3 docking-protein-protein-test.cfg

When I checked 'run1-test/00_topoaa' directory, I found several files like
down below
[image: image.png]

I'm sorry but I still have my doubts as to why the runtimeerror occurred.

Hyeonjae Lee

2022년 3월 1일 (화) 오후 4:56, Alexandre Bonvin ***@***.***>님이 작성:

**Comment by amjjbonvin** [comment]
The alpha release or the lasted main branch?
The latter is still evolving…

Check the out files for error messages.

**Comment by LoganLHJ** [comment]
I got it.. I just checked the main branch is still evolving..

Thank you for letting me know it, sir!

2022년 3월 1일 (화) 오후 5:13, Alexandre Bonvin ***@***.***>님이 작성:

**Comment by joaomcteixeira** [comment]
Hi @LoganLHJ 
However, the examples are all running on our hands in the `main` branch. 
Could you read here to see if it's a problem with your CNS? https://github.com/haddocking/haddock3/issues/329#issuecomment-1043554801

Can you set the tolerance to 20%? `tolerance = 20`.

**Comment by rvhonorato** [comment]
> Can you set the tolerance to 20%? tolerance = 20.

This does not make sense since you are getting errors in the topology, these must have 0% tolerance for errors, make sure your CNS installation works.
