### ISSUE TITLE
unexpected fail in particular example with `--extend-run`

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#449]
Identified by @PauAndrio in a video call

to reproduce:

1. `cd examples/docking-protein-protein`
1. run the -test.cfg but only with the topoaa module
1. copy the `run1-dir` folder to another folder `cp -r run1-test run-topaa`
2. prepare a cfg only with the rigidbody module
3. run `haddock3 rigid.cfg --extend-run run-topoaa`

output

```
[2022-05-31 11:12:40,402 __init__ INFO] [rigidbody] CNS jobs have finished
[2022-05-31 11:12:40,408 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.
Traceback (most recent call last):
  File "/trinity/login/joaomctx/haddock3/src/haddock/libs/libutil.py", line 341, in log_error_and_exit
    yield
  File "/trinity/login/joaomctx/haddock3/src/haddock/clis/cli.py", line 180, in main
    workflow.run()
  File "/trinity/login/joaomctx/haddock3/src/haddock/gear/extend_run.py", line 26, in run
    step.execute()
  File "/trinity/login/joaomctx/haddock3/src/haddock/libs/libworkflow.py", line 105, in execute
    module.run()
  File "/trinity/login/joaomctx/haddock3/src/haddock/modules/base_cns_module.py", line 48, in run
    self._run()
  File "/trinity/login/joaomctx/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 108, in _run
    self.export_output_models(faulty_tolerance=self.params["tolerance"])
  File "/trinity/login/joaomctx/haddock3/src/haddock/modules/__init__.py", line 243, in export_output_models
    self.finish_with_error(_msg)
  File "/trinity/login/joaomctx/haddock3/src/haddock/modules/__init__.py", line 252, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 20.00%.
[2022-05-31 11:12:40,412 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.
[2022-05-31 11:12:40,412 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2022-05-31 11:12:40,412 libutil INFO] Finished at 31/05/2022 11:12:40. For any help contact us at https://github.com/haddocking/haddoc
k3/issues. Adéu-siau! Dovidenia! Agur!.

```

**Comment by joaomcteixeira** [comment]
These two lines are written in the `inp` files for the normal run but are not written in the above example:

```
eval ($mol_fix_origin_2=false)                                                  
eval ($mol_shape_2=false) 
```
