### ISSUE TITLE
clarify chain matching error in caprieval

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#472]
the following error appears when chains of an input ensemble do not match properly:
```
Process Worker-27:
Traceback (most recent call last):
  File "/trinity/login/mgiulini/anaconda3/envs/haddock3_main/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/trinity/login/mgiulini/haddock3/src/haddock/libs/libparallel.py", line 28, in run
    task.run()
  File "/trinity/login/mgiulini/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 425, in run
    self.calc_irmsd(cutoff=irmsd_cutoff)
  File "/trinity/login/mgiulini/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 90, in calc_irmsd
    mod_coord_dic, _ = load_coords(
  File "/trinity/login/mgiulini/haddock3/src/haddock/libs/libalign.py", line 231, in load_coords
    min_idx = min(chain_dic[chain])
ValueError: min() arg is an empty sequence
```
Few things can be improved here:

- an `AlignError` must be raised
- the name and the features of the "problematic" model must be reported
- should we interrupt the overall `caprieval` module when this happens?

**Comment by mgiulini** [comment]
Related to #179 and #422

**Comment by joaomcteixeira** [comment]
To-do: Also test with :point_right: https://github.com/haddocking/haddock3/pull/144
