### ISSUE TITLE
Input PDB files without write permission lead to error in self-contained mode

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#598]
**Describe the bug**

When running in self-contained mode and the input PDB files have not write permission an error occurs when writing the files in the data dir of the run:

```[2022-12-17 15:37:48,192 libutil ERROR] [Errno 13] Permission denied: '../data/00_topoaa/1A2K_r_u.pdb'
Traceback (most recent call last):
  File "/trinity/home/software/software/haddock3/src/haddock/libs/libutil.py", line 305, in log_error_and_exit
    yield
  File "/trinity/home/software/software/haddock3/src/haddock/clis/cli.py", line 178, in main
    workflow.run()
  File "/trinity/home/software/software/haddock3/src/haddock/libs/libworkflow.py", line 37, in run
    step.execute()
  File "/trinity/home/software/software/haddock3/src/haddock/libs/libworkflow.py", line 130, in execute
    self.module.run()
  File "/trinity/home/software/software/haddock3/src/haddock/modules/base_cns_module.py", line 59, in run
    self._run()
  File "/trinity/home/software/software/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 179, in _run
    libpdb.sanitize(model,
  File "/trinity/home/software/software/haddock3/src/haddock/libs/libpdb.py", line 175, in sanitize
    with open(pdb_file_path, "w") as output_handler:
PermissionError: [Errno 13] Permission denied: '../data/00_topoaa/1A2K_r_u.pdb'
[2022-12-17 15:37:48,198 libutil ERROR] [Errno 13] Permission denied: '../data/00_topoaa/1A2K_r_u.pdb'
[2022-12-17 15:37:48,198 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
```

**To Reproduce**

Take one of the example, remove the write permission from the input PDB files and start a run.

**Expected behavior**

Writing of local files in the data dir of selfcontained run should be independent of the original file permissions.

**Comment by amjjbonvin** [comment]
Actually the error is also occurring in the default running mode (selfcontained = false)

**Comment by joaomcteixeira** [comment]
Correct. I will address this and finish testing #597 in the following days.
