### ISSUE TITLE
antigen-antibody docking: rcsb pdb fails, but alphafold pdb works? 

### ISSUE THREAD

**Issue by hyeh20** [haddocking/haddock3#694]
Hello, 
Thank you for all the work your team has put in to this! I was playing around with the antigen-antibody docking found here: https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/

I got the tutorial to run without an issue (antigen scenario 1). I then tried to switch up the antigen with another pdb, specifically 1OVA. I processed and cleaned the antigen with the following: 

```
pdb_fetch 1ova | pdb_tidy -strict | pdb_selchain -B | pdb_delhetatm | pdb_fixinsert | pdb_keepcoord | pdb_chain -B | pdb_chainxseg | pdb_tidy -strict > ab_processing/1ova_clean.pdb
```

I then proceeded to use the calc-accessibility.py script to generate antigen-surface.pass. I followed the rest of the tutorial thereafter exactly. When doing so, I get the error at the bottom of this post. Interestingly, when I use the AlphaFold prediction of ovalbumin (https://alphafold.ebi.ac.uk/entry/P01012) I do not have any issue and it runs just fine. I'm pretty new to working with HADDOCK, so hopefully its just a small mistake on my end somewhere. Thanks for the help! 

[2023-09-06 21:34:06,962 cli INFO] 
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.0 on 2023-09-06 21:34:00

Python 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0]

[2023-09-06 21:34:06,990 libutil WARNING] scenario1-surface-real/0_topoaa exists and it will be REMOVED!
[2023-09-06 21:34:06,992 libutil WARNING] scenario1-surface-real/data/0_topoaa exists and it will be REMOVED!
[2023-09-06 21:34:06,993 libutil WARNING] scenario1-surface-real/data/1_rigidbody exists and it will be REMOVED!
[2023-09-06 21:34:06,993 libutil WARNING] scenario1-surface-real/data/5_flexref exists and it will be REMOVED!
[2023-09-06 21:34:06,993 libutil WARNING] scenario1-surface-real/data/6_emref exists and it will be REMOVED!
[2023-09-06 21:34:06,994 prepare_run INFO] Uncompressing previous output files for folders: 
[2023-09-06 21:34:11,865 libworkflow INFO] Reading instructions step 0_topoaa
[2023-09-06 21:34:11,865 libworkflow INFO] Reading instructions step 1_rigidbody
[2023-09-06 21:34:11,865 libworkflow INFO] Reading instructions step 2_clustfcc
[2023-09-06 21:34:11,865 libworkflow INFO] Reading instructions step 3_seletopclusts
[2023-09-06 21:34:11,865 libworkflow INFO] Reading instructions step 4_caprieval
[2023-09-06 21:34:11,866 libworkflow INFO] Reading instructions step 5_flexref
[2023-09-06 21:34:11,866 libworkflow INFO] Reading instructions step 6_emref
[2023-09-06 21:34:11,867 libworkflow INFO] Reading instructions step 7_clustfcc
[2023-09-06 21:34:11,867 libworkflow INFO] Reading instructions step 8_seletopclusts
[2023-09-06 21:34:11,867 libworkflow INFO] Reading instructions step 9_caprieval
[2023-09-06 21:34:11,901 base_cns_module INFO] Running [topoaa] module
[2023-09-06 21:34:11,904 __init__ INFO] [topoaa] Molecule 1: ab_clean.pdb
[2023-09-06 21:34:11,941 __init__ INFO] [topoaa] Sanitizing molecule ab_clean.pdb
[2023-09-06 21:34:11,970 __init__ INFO] [topoaa] Topology CNS input created in ab_clean.inp
[2023-09-06 21:34:11,970 __init__ INFO] [topoaa] Molecule 2: 1ova_clean.pdb
[2023-09-06 21:34:11,972 __init__ INFO] [topoaa] Sanitizing molecule 1ova_clean.pdb
[2023-09-06 21:34:11,986 __init__ INFO] [topoaa] Topology CNS input created in 1ova_clean.inp
[2023-09-06 21:34:11,986 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2023-09-06 21:34:11,986 libutil INFO] Selected 2 cores to process 2 jobs, with 48 maximum available cores.
[2023-09-06 21:34:11,987 libparallel INFO] Using 2 cores
[2023-09-06 21:34:20,258 libparallel INFO] >> /ab_clean.inp completed 50% 
[2023-09-06 21:34:20,259 libparallel INFO] >> /1ova_clean.inp completed 100% 
[2023-09-06 21:34:20,259 libparallel INFO] 2 tasks finished
[2023-09-06 21:34:20,259 __init__ INFO] [topoaa] CNS jobs have finished
[2023-09-06 21:34:20,259 libutil ERROR] 50.00% of output was not generated for this module and tolerance was set to 0.00%.
Traceback (most recent call last):
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/libs/libutil.py", line 310, in log_error_and_exit
    yield
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/clis/cli.py", line 178, in main
    workflow.run()
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/libs/libworkflow.py", line 39, in run
    step.execute()
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/libs/libworkflow.py", line 143, in execute
    self.module.run()
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/modules/base_cns_module.py", line 59, in run
    self._run()
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 250, in _run
    self.export_output_models(faulty_tolerance=self.params["tolerance"])
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/modules/__init__.py", line 269, in export_output_models
    self.finish_with_error(_msg)
  File "/scratch/midway3/hughy/softwares/haddock3/src/haddock/modules/__init__.py", line 278, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 50.00% of output was not generated for this module and tolerance was set to 0.00%.
[2023-09-06 21:34:20,260 libutil ERROR] 50.00% of output was not generated for this module and tolerance was set to 0.00%.
[2023-09-06 21:34:20,260 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-09-06 21:34:20,260 libutil INFO] Finished at 06/09/2023 21:34:20. For any help contact us at https://github.com/haddocking/haddock3/issues. Até logo! Dovidenia! Au revoir!.

**Comment by amjjbonvin** [comment]
Did you visually check the PDB file of your antigen after the pdb preprocessing steps?

Could be a chain selection issue

**Comment by hyeh20** [comment]
Thanks for the tip, I suspect it may be due to pdb_fixinsert part of the antigen processing. Note that to generate the below figure I used chain A rather than chain B as noted in my original post (same error though). 
![ova1_processing](https://github.com/haddocking/haddock3/assets/17631691/710ce694-f868-4d93-864d-6e722762ade8)
