### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'

### ISSUE THREAD

**Issue by johnnytam100** [haddocking/haddock3#738]
Hi I tried to run an antibody-antigen docking example with 
`haddock3 docking-antibody-antigen-ranairCDR-clt-full.cfg`
However I got an error **No such file or directory: 'sbatch'**
May I know how to deal with this error?

[2023-10-30 01:09:43,705 cli INFO] 
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.0 on 2023-10-30 01:09:00

Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]

[2023-10-30 01:09:48,813 libworkflow INFO] Reading instructions step 0_topoaa
[2023-10-30 01:09:48,814 libworkflow INFO] Reading instructions step 1_rigidbody
[2023-10-30 01:09:48,814 libworkflow INFO] Reading instructions step 2_caprieval
[2023-10-30 01:09:48,814 libworkflow INFO] Reading instructions step 3_clustfcc
[2023-10-30 01:09:48,814 libworkflow INFO] Reading instructions step 4_seletopclusts
[2023-10-30 01:09:48,815 libworkflow INFO] Reading instructions step 5_caprieval
[2023-10-30 01:09:48,815 libworkflow INFO] Reading instructions step 6_flexref
[2023-10-30 01:09:48,815 libworkflow INFO] Reading instructions step 7_caprieval
[2023-10-30 01:09:48,816 libworkflow INFO] Reading instructions step 8_emref
[2023-10-30 01:09:48,816 libworkflow INFO] Reading instructions step 9_caprieval
[2023-10-30 01:09:48,816 libworkflow INFO] Reading instructions step 10_clustfcc
[2023-10-30 01:09:48,816 libworkflow INFO] Reading instructions step 11_seletopclusts
[2023-10-30 01:09:48,816 libworkflow INFO] Reading instructions step 12_caprieval
[2023-10-30 01:09:48,853 base_cns_module INFO] Running [topoaa] module
[2023-10-30 01:09:48,853 __init__ INFO] [topoaa] Molecule 1: 4G6K_fv.pdb
[2023-10-30 01:09:48,855 __init__ INFO] [topoaa] Sanitizing molecule 4G6K_fv.pdb
[2023-10-30 01:09:48,864 __init__ INFO] [topoaa] Topology CNS input created in 4G6K_fv.inp
[2023-10-30 01:09:48,864 __init__ INFO] [topoaa] Molecule 2: 4I1B-matched.pdb
[2023-10-30 01:09:48,865 __init__ INFO] [topoaa] Sanitizing molecule 4I1B-matched.pdb
[2023-10-30 01:09:48,872 __init__ INFO] [topoaa] Topology CNS input created in 4I1B-matched.inp
[2023-10-30 01:09:48,872 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2023-10-30 01:09:48,872 libhpc INFO] Concatenating, each .job will produce 5 (or less) models
[2023-10-30 01:09:48,872 libhpc INFO] > Running batch 1/1
[2023-10-30 01:09:48,881 libutil ERROR] [Errno 2] No such file or directory: 'sbatch'
**Traceback (most recent call last):
  File "/home/jupyter/script/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/home/jupyter/script/haddock3/src/haddock/clis/cli.py", line 185, in main
    workflow.run()
  File "/home/jupyter/script/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/home/jupyter/script/haddock3/src/haddock/libs/libworkflow.py", line 149, in execute
    self.module.run()  # type: ignore
  File "/home/jupyter/script/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/home/jupyter/script/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 215, in _run
    engine.run()
  File "/home/jupyter/script/haddock3/src/haddock/libs/libhpc.py", line 181, in run
    worker.run()
  File "/home/jupyter/script/haddock3/src/haddock/libs/libhpc.py", line 102, in run
    p = subprocess.run(shlex.split(cmd), capture_output=True)
  File "/opt/conda/envs/haddock3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/envs/haddock3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/envs/haddock3/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'**
[2023-10-30 01:09:48,882 libutil ERROR] [Errno 2] No such file or directory: 'sbatch'
[2023-10-30 01:09:48,882 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-10-30 01:09:48,883 libutil INFO] Finished at 30/10/2023 01:09:48. For any help contact us at https://github.com/haddocking/haddock3/issues. Agur! Ciao! Dovidenia!.

**Comment by amjjbonvin** [comment]
You must be running in HPC mode.

Is slurm installed on your system?
sbatch is the command used to submit jobs to the batch system.

**Comment by mgiulini** [comment]
hi there, it didn't work because by default this example runs in "hpc" mode, which requires the configuration of slurm/PBS. If you substitute mode = "hpc" with `mode = "local"` in the header it should work!
