### ISSUE TITLE
haddock3 run fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by sujankd** [haddocking/haddock3#746]
Hi,

I am trying to run haddock3 for antibody-antigen docking on Ubuntu 18.04 platform. The run fails after the cns step.

The log file and my cfg are enclosed below. Please suggest. Thanks lot.

------
log file
---------
[2023-11-30 16:33:34,757 cli INFO] 
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.0 on 2023-11-30 16:33:00

Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32) 
[GCC 12.3.0]

[2023-11-30 16:33:39,668 libworkflow INFO] Reading instructions step 0_topoaa
[2023-11-30 16:33:39,669 libworkflow INFO] Reading instructions step 1_rigidbody
[2023-11-30 16:33:39,669 libworkflow INFO] Reading instructions step 2_seletop
[2023-11-30 16:33:39,669 libworkflow INFO] Reading instructions step 3_flexref
[2023-11-30 16:33:39,670 libworkflow INFO] Reading instructions step 4_emref
[2023-11-30 16:33:39,670 libworkflow INFO] Reading instructions step 5_clustfcc
[2023-11-30 16:33:39,670 libworkflow INFO] Reading instructions step 6_caprieval
[2023-11-30 16:33:39,705 base_cns_module INFO] Running [topoaa] module
[2023-11-30 16:33:39,705 __init__ INFO] [topoaa] Molecule 1: frhu_clean.pdb
[2023-11-30 16:33:39,707 __init__ INFO] [topoaa] Sanitizing molecule frhu_clean.pdb
[2023-11-30 16:33:39,720 __init__ INFO] [topoaa] Topology CNS input created in frhu_clean.inp
[2023-11-30 16:33:39,720 __init__ INFO] [topoaa] Molecule 2: 1dfv_clean.pdb
[2023-11-30 16:33:39,722 __init__ INFO] [topoaa] Sanitizing molecule 1dfv_clean.pdb
[2023-11-30 16:33:39,733 __init__ INFO] [topoaa] Topology CNS input created in 1dfv_clean.inp
[2023-11-30 16:33:39,734 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2023-11-30 16:33:39,734 libutil INFO] Selected 2 cores to process 2 jobs, with 40 maximum available cores.
[2023-11-30 16:33:39,734 libparallel INFO] Using 2 cores
[2023-11-30 16:33:44,964 libparallel INFO] >> /frhu_clean.inp completed 50% 
[2023-11-30 16:33:44,965 libparallel INFO] >> /1dfv_clean.inp completed 100% 
[2023-11-30 16:33:44,965 libparallel INFO] 2 tasks finished
[2023-11-30 16:33:44,965 __init__ INFO] [topoaa] CNS jobs have finished
[2023-11-30 16:33:44,967 libutil ERROR] dictionary changed size during iteration
Traceback (most recent call last):
  File "/media/AbD/tools/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/media/AbD/tools/haddock3/src/haddock/clis/cli.py", line 185, in main
    workflow.run()
  File "/media/AbD/tools/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/media/AbD/tools/haddock3/src/haddock/libs/libworkflow.py", line 149, in execute
    self.module.run()  # type: ignore
  File "/media/AbD/tools/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/media/AbD/tools/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 247, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/media/AbD/tools/haddock3/src/haddock/modules/__init__.py", line 285, in export_io_models
    faulty = io.check_faulty()
  File "/media/AbD/tools/haddock3/src/haddock/libs/libontology.py", line 214, in check_faulty
    self.remove_missing()
  File "/media/AbD/tools/haddock3/src/haddock/libs/libontology.py", line 224, in remove_missing
    for key2 in element:
RuntimeError: dictionary changed size during iteration
[2023-11-30 16:33:44,969 libutil ERROR] dictionary changed size during iteration
[2023-11-30 16:33:44,969 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-11-30 16:33:44,970 libutil INFO] Finished at 30/11/2023 16:33:44. For any help contact us at https://github.com/haddocking/haddock3/issues. Good bye! Até logo! Adéu-siau!.

----------------
cfg file
-----------------
# ====================================================================
#  docking experiment for ab00

# directory in which the scoring will be done
run_dir = "run1"
# compute mode
mode = "local"
ncores = 40

# molecules to be docked
molecules =  [
    "frhu_clean.pdb",
    "1dfv_clean.pdb"
    ]

# parameters

[topoaa]

[rigidbody]
# CDR to surface ambig restraints
ambig_fname = "ambig_paratope_surface.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"
# Turn off random removal of restraints
randremoval = false

[seletop]

[flexref]
# CDR to surface ambig restraints
ambig_fname = "ambig_paratope_surface.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"
# Turn off random removal of restraints
randremoval = false

[emref]
# CDR to surface ambig restraints
ambig_fname = "ambig_paratope_surface.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"
# Turn off random removal of restraints
randremoval = false

[clustfcc]
threshold = 10

[caprieval]

# ====================================================================

**Comment by amjjbonvin** [comment]
First make sure that your CNS installation was successful.

Can you start CNS manually from the command line (e.g. calling it from haddock3/bin/cns)?

**Comment by sujankd** [comment]
> hi, can you share with us the two input molecules and the .tbl files?

Here is a zip archive containing the two .tbl files and the two molecules - 1dfv_clean.pdb (antigen) and frhu_clean.pdb (antibody). I have cleaned up the molecules following instructions in Haddock3 antigen-antibody tutorial. Thanks for the help.

[run1.zip](https://github.com/haddocking/haddock3/files/13516557/run1.zip)

**Comment by sujankd** [comment]
> First make sure that your CNS installation was successful. Can you start CNS manually from the command line (e.g. calling it from haddock3/bin/cns)?

Yes, CNS installation was clean. I am able to run cns from command line.

**Comment by sujankd** [comment]
> I run a quick test. The problem is that you have overlapping residue numbering and because of that CNS stops with the following error message (found in 1dfv_clean.out.gz in the 0_topoaa directory):
> 
> ```
>  COOR>ATOM      1  N   SER B   5      96.417  27.571  50.474  1.00 59.67      B    N
>  %SEGMNT-ERR: attempt to enter duplicate residue B    5    SER
>  %SEGMNT error encountered:  check PDB file for residue duplications.
> ...
> ```
> 
> You must have missed some steps in the antibody preparation, shifting the residue numbering of the second chain to avoid overlap.

Thank you very much for the lead! The molecule in question is my antigen which is in a homodimer form. So I shifted the 2nd chain residues in a way similar to what I did for the antibody. Also added the antigen to the unambiguous restraints using restrain_bodies script and was able to successfully complete the run.

Thanks once again. .. and Cheers!
