### ISSUE TITLE
[libutil ERROR] list index out of range 

### ISSUE THREAD

**Issue by AnastasiiaDuchenko** [haddocking/haddock3#754]
**Error: list index out of range**
It occurred when I executed "run_tests.py" using Slurm on HPC..

**To Reproduce**
1. When executing 'run_tests.py' with Slurm on HPC, and with local test the same.
2. The test with CNS_solve_1.3 was successful.

**Configuration (optional - remove if not relevant)**
 - OS: Mac, HPC
 - Haddock 3.0, CNS_solve_1.3
 - Python 3.9.18

**Full log error after local test**:
[2023-12-06 12:34:36,768 init INFO] [topoaa] Topology CNS input created in 4I1B-matched.inp
[2023-12-06 12:34:36,768 init INFO] [topoaa] Running CNS Jobs n=2
[2023-12-06 12:34:36,769 libutil INFO] Selected 2 cores to process 2 jobs, with 8 maximum available cores.
[2023-12-06 12:34:36,769 libparallel INFO] Using 2 cores
Process Worker-1:
Process Worker-2:
Traceback (most recent call last):
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libparallel.py", line 68, in run
task.run()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libsubprocess.py", line 190, in run
p = subprocess.Popen(
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 1837, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/users/aduchenk/software/haddock3/bin/cns')
Traceback (most recent call last):
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libparallel.py", line 68, in run
task.run()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libsubprocess.py", line 190, in run
p = subprocess.Popen(
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 1837, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/users/aduchenk/software/haddock3/bin/cns')
[2023-12-06 12:34:36,788 libparallel INFO] >> /4G6K_fv.inp completed 50%
[2023-12-06 12:34:36,789 libparallel INFO] >> /4I1B-matched.inp completed 100%
[2023-12-06 12:34:36,789 libparallel INFO] 2 tasks finished
[2023-12-06 12:34:36,789 init INFO] [topoaa] CNS jobs have finished
[2023-12-06 12:34:36,790 libutil ERROR] dictionary changed size during iteration
Traceback (most recent call last):
File "/users/aduchenk/software/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
yield
File "/users/aduchenk/software/haddock3/src/haddock/clis/cli.py", line 185, in main
workflow.run()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
step.execute()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libworkflow.py", line 149, in execute
self.module.run() # type: ignore
File "/users/aduchenk/software/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
self._run()
File "/users/aduchenk/software/haddock3/src/haddock/modules/topology/topoaa/init.py", line 247, in _run
self.export_io_models(faulty_tolerance=self.params["tolerance"])
File "/users/aduchenk/software/haddock3/src/haddock/modules/init.py", line 285, in export_io_models
faulty = io.check_faulty()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libontology.py", line 214, in check_faulty
self.remove_missing()
File "/users/aduchenk/software/haddock3/src/haddock/libs/libontology.py", line 224, in remove_missing
for key2 in element:
RuntimeError: dictionary changed size during iteration
[2023-12-06 12:34:36,793 libutil ERROR] dictionary changed size during iteration
[2023-12-06 12:34:36,793 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.

**Comment by amjjbonvin** [comment]
First of all - don't put the description of the problem all in the title... Please update your issue so that it becomes readable. 

And a few first questions:

1) Did you try to run locally instead of via slurm?

2) Can you start cns manually to make sure it works?

**Comment by AnastasiiaDuchenko** [comment]
1. I tested CNS_solve_1.3. It works.
2. then I tried run haddock3 locally. 
- Commands: "conda activate haddock3. cd examples/ . python3 run_tests.py -b" I got error:
[2023-12-06 12:34:36,768 __init__ INFO] [topoaa] Topology CNS input created in 4I1B-matched.inp
[2023-12-06 12:34:36,768 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2023-12-06 12:34:36,769 libutil INFO] Selected 2 cores to process 2 jobs, with 8 maximum available cores.
[2023-12-06 12:34:36,769 libparallel INFO] Using 2 cores
Process Worker-1:
Process Worker-2:
Traceback (most recent call last):
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libparallel.py", line 68, in run
    task.run()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libsubprocess.py", line 190, in run
    p = subprocess.Popen(
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/users/aduchenk/software/haddock3/bin/cns')
Traceback (most recent call last):
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libparallel.py", line 68, in run
    task.run()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libsubprocess.py", line 190, in run
    p = subprocess.Popen(
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/users/aduchenk/software/haddock3/bin/cns')
[2023-12-06 12:34:36,788 libparallel INFO] >> /4G6K_fv.inp completed 50% 
[2023-12-06 12:34:36,789 libparallel INFO] >> /4I1B-matched.inp completed 100% 
[2023-12-06 12:34:36,789 libparallel INFO] 2 tasks finished
[2023-12-06 12:34:36,789 __init__ INFO] [topoaa] CNS jobs have finished
[2023-12-06 12:34:36,790 libutil ERROR] dictionary changed size during iteration
Traceback (most recent call last):
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/users/aduchenk/software/haddock3/src/haddock/clis/cli.py", line 185, in main
    workflow.run()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libworkflow.py", line 149, in execute
    self.module.run()  # type: ignore
  File "/users/aduchenk/software/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/users/aduchenk/software/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 247, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/users/aduchenk/software/haddock3/src/haddock/modules/__init__.py", line 285, in export_io_models
    faulty = io.check_faulty()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libontology.py", line 214, in check_faulty
    self.remove_missing()
  File "/users/aduchenk/software/haddock3/src/haddock/libs/libontology.py", line 224, in remove_missing
    for key2 in element:
RuntimeError: dictionary changed size during iteration
[2023-12-06 12:34:36,793 libutil ERROR] dictionary changed size during iteration
[2023-12-06 12:34:36,793 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.

**Comment by AnastasiiaDuchenko** [comment]
Hi. Thank you for your response. I changed the issues as you indicated.
1. Yes. I got the same error (On the top in details)
2. CNS checked locally. It works.
Do you have any suggestions on what I can check or fix?

**Comment by amjjbonvin** [comment]
There is an error stating CNS is the wrong architecture…

OSError: [Errno 8] Exec format error: PosixPath('/users/aduchenk/software/haddock3/bin/cns')

**Comment by AnastasiiaDuchenko** [comment]
Ok. I'll try to kill and reinstall everything. Thank you for your help.

**Comment by AnastasiiaDuchenko** [comment]
I killed and installed haddock3 and cns from scratch. After executing haddock3 run_test.py: 

Starting HADDOCK 3.0.0 on 2023-12-07 11:22:00

Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]

[2023-12-07 11:22:06,750 libutil ERROR] Something is wrong with the config file.
Traceback (most recent call last):
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/gear/config.py", line 219, in loads
    cfg_dict = toml.loads(cfg)  # Try to load it with the toml library
  File "/users/aduchenk/.conda/envs/haddock3/lib/python3.9/site-packages/toml/decoder.py", line 260, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: '"'. Try quoting the key name. (line 1 column 3 char 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/gear/config.py", line 138, in load
    return loads(Path(fpath).read_text())
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/gear/config.py", line 221, in loads
    raise ConfigurationError(
haddock.core.exceptions.ConfigurationError: Some thing is wrong with the config file: Found invalid character in key name: '"'. Try quoting the key name. (line 1 column 3 char 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/clis/cli.py", line 143, in main
    params, other_params = setup_run(
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/gear/prepare_run.py", line 248, in setup_run
    config_files = read_config(workflow_path)
  File "/users/aduchenk/software/haddock3/haddock3/src/haddock/gear/config.py", line 140, in load
    raise ConfigurationError(
haddock.core.exceptions.ConfigurationError: Something is wrong with the config file.
[2023-12-07 11:22:06,751 libutil ERROR] Something is wrong with the config file.
[2023-12-07 11:22:06,751 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-12-07 11:22:06,751 libutil INFO] Finished at 07/12/2023 11:22:06. For any help contact us at https://github.com/haddocking/haddock3/issues. Ciao! Até logo! Dovidenia!.
(haddock3) [aduchenk@str-i2 examples]$

**Comment by amjjbonvin** [comment]
Ah! You want to run the haddock3 tests from the example directory!

run_test.py is not a haddock3 config file, but a python file that will call haddock3 to run the tests

Proper usage is:  python3 run_test.py


> 
> I killed and installed haddock3 and cns from scratch. After executing haddock3 run_test.py:
> 
> 
>

**Comment by AnastasiiaDuchenko** [comment]
Installation of haddock3 and CNS from scratch Helped. Tests executing "python3 run_test.py" and "haddock3 docking-antibody-antigen-CDR-accessible-clt-test.cfg" working in local mode.
I still have an issue with HPC mode, but this issue could be closed.
