### ISSUE TITLE
Error on flexref docking step

### ISSUE THREAD

**Issue by steven0seagal** [haddocking/haddock3#824]
**Describe the bug**
Hi I have recently used your tool to dock some proteins obtained from Alphafold2 to membrane protein deposited in RSCB  database (7URX). After starting haddock I get this error:
```
##############################################  
# #  
# HADDOCK 3 #  
# #  
##############################################

Starting HADDOCK 3.0.0 on 2024-03-14 16:33:00

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

[2024-03-14 16:34:33,787 libutil ERROR] 5.00% of output was not generated for this module and tolerance was set to 5.00%.  
Traceback (most recent call last):  
File "/haddock/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit  
yield  
File "/haddock/haddock3/src/haddock/clis/cli.py", line 185, in main  
workflow.run()  
File "/haddock/haddock3/src/haddock/libs/libworkflow.py", line 43, in run  
step.execute()  
File "/haddock/haddock3/src/haddock/libs/libworkflow.py", line 155, in execute  
self.module.run() # type: ignore  
File "/haddock/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run  
self._run()  
File "/haddock/haddock3/src/haddock/modules/refinement/flexref/__init__.py", line 136, in _run  
self.export_io_models(faulty_tolerance=self.params["tolerance"])  
File "/haddock/haddock3/src/haddock/modules/__init__.py", line 291, in export_io_models  
self.finish_with_error(_msg)  
File "/haddock/haddock3/src/haddock/modules/__init__.py", line 300, in finish_with_error  
raise RuntimeError(reason)  
RuntimeError: 5.00% of output was not generated for this module and tolerance was set to 5.00%.  
[2024-03-14 16:34:33,787 libutil ERROR] 5.00% of output was not generated for this module and tolerance was set to 5.00%.  
[2024-03-14 16:34:33,787 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.

```
My installation is correct because I started many other jobs and they completed. 

My run_param file is :

```
run_dir = "/haddock/output/1"
mode = "local"
ncores = 20
self_contained = true
postprocess = true
clean= true
molecules = ["/haddock/input/lead.pdb", "/haddock/input/target.pdb"]
[topoaa]
[rigidbody]
ambig_fname = "/haddock/input/0-0-ambig.tbl"
randremoval = false
sampling =1000
[caprieval]
[seletop]
select = 200
[flexref]
tolerance = 5
ambig_fname = "/haddock/input/0-0-ambig.tbl"
randremoval = false
[caprieval]
[emref]
ambig_fname = "/haddock/input/0-0-ambig.tbl"
randremoval = false
[clustfcc]
[seletopclusts]
top_cluster = 20
[caprieval]
```

In output directory I found out that whole process stops at flexref step. And in some files I found this lines:
```
 
 NBONDS: found   135422 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 %atoms "A   -48  -LYS -NZ  " and "A   -48  -LYS -C   " only  0.32 A apart
 NBONDS: found    19614 intra-atom interactions
 NBONDS: found        1 nonbonded violations
 NBONDS: found        0 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found   135433 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found    17759 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found   135455 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 NBONDS: found        0 intra-atom interactions
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -N   "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -HN  "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -CA  "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -CB  "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -CG1 "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -CG2 "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -C   "
 %ATMCHK-ERR: unknown coordinates for atom "A   -1   -VAL -O   "
 %ATMCHK-ERR: unknown coordinates for atom "A   -2   -LYS -N   "
 %ATMCHK-ERR: unknown coordinates for atom "A   -2   -LYS -HN  "
 %ATMCHK-ERR: unknown coordinates for atom "A   -2   -LYS -CA  "
...

 %ATMCHK-ERR: unknown coordinates for atom "A   -76  -ALA -C   "
 %ATMCHK-ERR: unknown coordinates for atom "A   -76  -ALA -O   "
 %ATMCHK error encountered: Unknown coordinates
   (CNS is in mode: SET ABORT=NORMal END)
 *****************************************************
 ABORT mode will terminate program execution. 
 *****************************************************
 Program will stop immediately.
          ============================================================
           Maximum dynamic memory allocation:  2997838712 bytes
           Maximum dynamic memory overhead:          4864 bytes
           Program started at: 16:33:44 on 14-Mar-2024
           Program stopped at: 16:34:09 on 14-Mar-2024
           CPU time used:      25.3773 seconds
          ============================================================

```
What can cause such problem ? 

My input data 
[input.zip](https://github.com/haddocking/haddock3/files/14605547/input.zip)

**Comment by amjjbonvin** [comment]
This is more a question from our support forum at ask.bioexcel.eu  - not a HADDOCK issue.

Most likely your input models have clashes that cause the flexible refinement to crash.
You could try running first some minimisation of your models. You can also use haddock3 for that, simply providing only one protein and running emref.

Or try adding a emref module before the flexref one
