### ISSUE TITLE
50.00% of output was not generated for this module and tolerance was set to 0.00%.

### ISSUE THREAD

**Issue by Yuanhang2024** [haddocking/haddock3#884]
**Describe the bug**
```
[2024-05-04 22:03:31,746 libutil ERROR] 50.00% of output was not generated for this module and tolerance was set to 0.00%.
```

**To Reproduce**
Running with Config below:
```
# ====================================================================
# Protein-ligand docking example

# directory in which the scoring will be done
run_dir = "Nb17-ID3239"

# execution mode
mode = "local"
ncores = 40
# in which queue the jobs should run, if nothing is defined
#  it will take the system's default
# queue = "short"
# concatenate models inside each job, concat = 5 each .job will produce 5 models
concat = 5
#  Limit the number of concurrent submissions to the queue
queue_limit = 100

# molecules to be docked
molecules =  [
    "data/6vxf_ABCG2.pdb",
    "data/CycPeptMPDB_ID_3239_ChainB.pdb"
    ]

# ====================================================================
[topoaa]
autohis = true
ligand_param_fname = "data/ligand-prodrg.param"
ligand_top_fname = "data/ligand-prodrg.top"
delenph = false

[rigidbody]
tolerance = 5
ambig_fname = "data/ambig-active-rigidbody.tbl"
ligand_param_fname = "data/ligand-prodrg.param"
ligand_top_fname = "data/ligand-prodrg.top"
sampling = 20
w_vdw = 1.0

[caprieval]

[seletop]
select = 200

[caprieval]


[flexref]
tolerance = 5
ambig_fname = "data/ambig-passive.tbl"
ligand_param_fname = "data/ligand-prodrg.param"
ligand_top_fname = "data/ligand-prodrg.top"
mdsteps_rigid = 0
mdsteps_cool1 = 0

[caprieval]


[rmsdmatrix]
resdic_A = [247,248,249,250,251,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,]
resdic_B = [ 1 ]

[clustrmsd]
criterion = 'maxclust'
n_clusters = 4 # the number of clusters to be formed

[seletopclusts]
top_models = 4

[caprieval]

# ====================================================================
```

**Expected behavior**

**Configuration (optional - remove if not relevant)**
 - OS:CentOS

**Comment by Yuanhang2024** [comment]
The examples from the protein-ligand-docking folder can run normally.

**Comment by amjjbonvin** [comment]
It’s not a bug - most likely bad quality of your staring models - or a problem with the ligand param/topo files

These are required if you want to dock some other ligands and should be provided to haddock

Our haddock2.4 server generate those automatically. The standalone version does not

**Comment by Yuanhang2024** [comment]
Thank you so much for answering, but I have 5000 samples to deal with, so I can't rely on the server. How can I generate the .top and .param files in large scales?

**Comment by amjjbonvin** [comment]
Some tips can be found at:

https://www.bonvinlab.org/software/haddock2.4/faq/#small-ligand-docking-with-haddock￼
HADDOCK2.4 manual - Frequently Asked Questions
bonvinlab.org

Further you could check the BioExcel BioBB modules. There is one to generate CNS topo/param file using acepype

Check: https://github.com/bioexcel/biobb_wf_ligand_parameterization  (look for the CNS parametrisation tutorial)

**Comment by Yuanhang2024** [comment]
I've used acpype to generate .top and .par files in CNS standards, but the same error repeated.

**Comment by amjjbonvin** [comment]
Check the out files in the 00_topoaa directory for error messages, starting from the end of the file

Did you define the correct file names in the config file? And your ligand should have a chainID defined in the PDB file

**Comment by Yuanhang2024** [comment]
Error message be like this:

 File "/public/home/acosdmq0yn/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 79, in _run
    sampling_factor = int(self.params["sampling"] / len(models_to_dock))
ZeroDivisionError: division by zero
[2024-05-11 01:18:59,632 libutil ERROR] division by zero

**Comment by Yuanhang2024** [comment]
Config file names have been corrected, and ligand chain ID have been defined and used in the .tbl file.

**Comment by Yuanhang2024** [comment]
![image](https://github.com/haddocking/haddock3/assets/168916290/1c264c45-a601-4340-b562-10ab1be8f08e)
Screenshot of the ligand

**Comment by Yuanhang2024** [comment]
[PeptideDocking3239.zip](https://github.com/haddocking/haddock3/files/15280997/PeptideDocking3239.zip)
The running dir is here.

**Comment by VGPReys** [comment]
Is your issue solved ?

**Comment by Shunamo** [comment]
I faced the same issue.

**Comment by mgiulini** [comment]
can you provide us with some more details? are you trying to dock a ligand to a protein? when you see this message after the `topoaa` module it typically means that something is wrong with one of your input structures

**Comment by Shunamo** [comment]
```
Starting HADDOCK 3.0.0 on 2024-08-09 17:57:00

Python 3.9.19 (main, Jul 23 2024, 07:17:30) 
[GCC 10.2.1 20210110]

[2024-08-09 17:57:40,698 libworkflow INFO] Reading instructions step 0_topoaa
[2024-08-09 17:57:40,698 libworkflow INFO] Reading instructions step 1_rigidbody
[2024-08-09 17:57:40,698 libworkflow INFO] Reading instructions step 2_seletop
[2024-08-09 17:57:40,698 libworkflow INFO] Reading instructions step 3_flexref
[2024-08-09 17:57:40,699 libworkflow INFO] Reading instructions step 4_emref
[2024-08-09 17:57:40,699 libworkflow INFO] Reading instructions step 5_clustfcc
[2024-08-09 17:57:40,699 libworkflow INFO] Reading instructions step 6_seletopclusts
[2024-08-09 17:57:40,720 base_cns_module INFO] Running [topoaa] module
[2024-08-09 17:57:40,720 __init__ INFO] [topoaa] Molecule 1: fixed_H5_1.pdb
[2024-08-09 17:57:40,722 __init__ INFO] [topoaa] Sanitizing molecule fixed_H5_1.pdb
[2024-08-09 17:57:40,729 __init__ INFO] [topoaa] Topology CNS input created in fixed_H5_1.inp
[2024-08-09 17:57:40,729 __init__ INFO] [topoaa] Molecule 2: fixed_IL4R_structure.pdb
[2024-08-09 17:57:40,732 __init__ INFO] [topoaa] Sanitizing molecule fixed_IL4R_structure.pdb
[2024-08-09 17:57:40,750 __init__ INFO] [topoaa] Topology CNS input created in fixed_IL4R_structure.inp
[2024-08-09 17:57:40,750 __init__ INFO] [topoaa] Running CNS Jobs n=2
[2024-08-09 17:57:40,750 libutil INFO] Selected 2 cores to process 2 jobs, with 48 maximum available cores.
[2024-08-09 17:57:40,750 libparallel INFO] Using 2 cores
[2024-08-09 17:57:41,547 libparallel INFO] >> completed 50% 
[2024-08-09 17:57:43,526 libparallel INFO] >> completed 100% 
[2024-08-09 17:57:43,526 libparallel INFO] 2 tasks finished
[2024-08-09 17:57:43,526 __init__ INFO] [topoaa] CNS jobs have finished
[2024-08-09 17:57:43,528 base_cns_module INFO] Module [topoaa] finished.
[2024-08-09 17:57:43,528 __init__ INFO] [topoaa] took 3 seconds
[2024-08-09 17:57:44,113 base_cns_module INFO] Running [rigidbody] module
[2024-08-09 17:57:44,114 __init__ INFO] [rigidbody] crossdock=true
[2024-08-09 17:57:44,114 __init__ INFO] [rigidbody] Preparing jobs...
[2024-08-09 17:57:44,351 __init__ INFO] [rigidbody] Running CNS Jobs n=60
[2024-08-09 17:57:44,351 libutil INFO] Selected 4 cores to process 60 jobs, with 48 maximum available cores.
[2024-08-09 17:57:44,351 libparallel INFO] Using 4 cores
[2024-08-09 17:57:45,972 libparallel INFO] >> completed 10% 
[2024-08-09 17:57:45,972 libparallel INFO] >> completed 20% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 30% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 40% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 50% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 60% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 70% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 80% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 90% 
[2024-08-09 17:57:46,386 libparallel INFO] >> completed 100% 
[2024-08-09 17:57:46,386 libparallel INFO] 60 tasks finished
[2024-08-09 17:57:46,386 __init__ INFO] [rigidbody] CNS jobs have finished
[2024-08-09 17:57:46,408 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 50.00%.
Traceback (most recent call last):
  File "/software/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/software/haddock3/src/haddock/clis/cli.py", line 185, in main
    workflow.run()
  File "/software/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/software/haddock3/src/haddock/libs/libworkflow.py", line 155, in execute
    self.module.run()  # type: ignore
  File "/software/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/software/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 159, in _run
    self.export_io_models(faulty_tolerance=self.params["tolerance"])
  File "/software/haddock3/src/haddock/modules/__init__.py", line 291, in export_io_models
    self.finish_with_error(_msg)
  File "/software/haddock3/src/haddock/modules/__init__.py", line 300, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 50.00%.
[2024-08-09 17:57:46,409 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 50.00%.
[2024-08-09 17:57:46,409 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-08-09 17:57:46,409 libutil INFO] Finished at 09/08/2024 17:57:46. For any help contact us at https://github.com/haddocking/haddock3/issues. Agur! Good bye! Dovidenia!.
```

This is the log file I got. I got a problem that was in the issue at first, so I modified the pdb file through pdbFixer and ran haddock in my container again, and I got this error message. How do I fix it?

**Comment by amjjbonvin** [comment]
Check one of the output file in the rigidbody directory of the run.
Look for error messages starting at the bottom of the file

**Comment by alchemistcai** [comment]
I met the same problem recently.I used acpype to generate top and par files and 2/3 ligands  failed to generate in topoaa module.

In topoaa directory,the output of cns says there are missing dihedral constants.

I tried some methods and here is my solution.As acpype use sdm to optimize for minutes,I only test my 2 failure ligands.I hope this helps:

```bash
obabel -ipdb [your_original_ligand].pdb -O ligand.pdb -h
acpype -i ligand.pdb -o cns -t -j -a amber
```

Then use ligand_NEW.pdb(each atom name is unique),ligand_CNS.top,ligand_CNS.par in generated directory.They are altered to chain Z and residue id 1,don't forget to modify ligand_NEW.pdb or tbl restraint file to be consistent.

**Comment by liu1441452945** [comment]
Hello, I encountered the same issue. My antibody was generated using IgFold and contains both heavy and light chains. When I use either the heavy or the light chain alone for docking, it runs successfully. However, when my ligand PDB file contains both the heavy and light chains simultaneously, it results in an error.  

This is my original PDB 
```
 ATOM   1913  O   SER H 113      -3.046  18.346  23.145  1.00  0.31           O  
ATOM   1914  OXT SER H 113      -3.474  18.005  21.091  1.00  0.31           O  
ATOM   1915  CB  SER H 113      -0.415  17.329  22.792  1.00  0.31           C  
ATOM   1916  OG  SER H 113      -0.809  17.635  24.100  1.00  0.31           O  
ATOM   1917  H   SER H 113      -0.410  17.181  20.218  1.00  0.31           H  
ATOM   1918  HA  SER H 113      -1.943  15.901  22.367  1.00  0.31           H  
ATOM   1919 1HB  SER H 113       0.352  16.554  22.811  1.00  0.31           H  
ATOM   1920 2HB  SER H 113       0.022  18.211  22.326  1.00  0.31           H  
ATOM   1921  HG  SER H 113      -0.021  17.955  24.546  1.00  0.31           H  
TER    1922      SER H 113                                                       
ATOM   1922  N   ASP L   1      15.094  -6.002   2.018  1.00  0.51           N  
ATOM   1923  CA  ASP L   1      13.997  -5.352   1.317  1.00  0.51           C  
ATOM   1924  C   ASP L   1      14.494  -4.828  -0.024  1.00  0.51           C  
ATOM   1925  O   ASP L   1      15.559  -4.216  -0.092  1.00  0.51           O  
ATOM   1926  CB  ASP L   1      13.458  -4.183   2.149  1.00  0.51           C  
ATOM   1927  CG  ASP L   1      12.874  -4.615   3.498  1.00  0.51           C  
ATOM   1928  OD1 ASP L   1      12.638  -5.792   3.678  1.00  0.51           O  
ATOM   1929  OD2 ASP L   1      12.671  -3.757   4.338  1.00  0.51           O 
```
 This is the file in which I later modified the residue numbering information.
```
ATOM   1913  O   SER H 113      -3.046  18.346  23.145  1.00  0.31           O  
ATOM   1914  CB  SER H 113      -0.415  17.329  22.792  1.00  0.31           C  
ATOM   1915  OG  SER H 113      -0.809  17.635  24.100  1.00  0.31           O  
ATOM   1916  OXT SER H 113      -3.474  18.005  21.091  1.00  0.31           O1-
ATOM   1917  H   SER H 113      -0.410  17.181  20.218  1.00  0.31           H  
ATOM   1918  HA  SER H 113      -1.943  15.901  22.367  1.00  0.31           H  
ATOM   1919 1HB  SER H 113       0.352  16.554  22.811  1.00  0.31           H  
ATOM   1920 2HB  SER H 113       0.022  18.211  22.326  1.00  0.31           H  
ATOM   1921  HG  SER H 113      -0.021  17.955  24.546  1.00  0.31           H  
TER   
ATOM   1922  N   ASP L 114      15.094  -6.002   2.018  1.00  0.51           N  
ATOM   1923  CA  ASP L 114      13.997  -5.352   1.317  1.00  0.51           C  
ATOM   1924  C   ASP L 114      14.494  -4.828  -0.024  1.00  0.51           C  
ATOM   1925  O   ASP L 114      15.559  -4.216  -0.092  1.00  0.51           O  
ATOM   1926  CB  ASP L 114      13.458  -4.183   2.149  1.00  0.51           C  
ATOM   1927  CG  ASP L 114      12.874  -4.615   3.498  1.00  0.51           C  
ATOM   1928  OD1 ASP L 114      12.638  -5.792   3.678  1.00  0.51           O  
ATOM   1929  OD2 ASP L 114      12.671  -3.757   4.338  1.00  0.51           O1-
```

 I performed docking using both PDB files separately, but both resulted in errors. I'm not sure which specific residue numbering needs to be corrected. I would greatly appreciate any guidance or suggestions on how to resolve this issue.

**Comment by amjjbonvin** [comment]
The problem could come from clashes between your chains that cause the system to “explode” during refinement.

Try first minimising your antibody alone (check for example the emscoring or mdscoring examples)

**Comment by liu1441452945** [comment]
> Also, please check the antibody tutorial we have online: https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/
> 
> You will see that we advise to merge both heavy (H) and light (L) chains into a single one (let's say B), and add body-restraints (you can generate them using `>haddock3-restraints restrain_bodies IgFold_HLmerged_to_B.pdb > ab_restraints.tbl`) as unambiguous restraints (`unambig_fname= "ab_restraints.tbl"`) to keep the two chains together. If you don't, you will be performing a **3-body docking**.

Thank you very much! I followed the steps you provided to merge the two chains into a single chain, and HADDOCK ran successfully. I truly appreciate you taking the time to respond despite your busy schedule.
