### ISSUE TITLE
Use `prepare_cns_input_sequential` when `mode=mpi`

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#940]
**Describe the bug**

Some of the last changes have caused a bug in the MPI mode of haddock3. I am getting the following error (both on Lumi and on our own cluster):

```
[2024-07-16 10:51:09,059 libmpi INFO] Executing tasks with the haddock3-mpitask runner using 100 processors...
[2024-07-16 10:51:12,755 libutil ERROR]
Traceback (most recent call last):
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/clis/cli.py", line 187, in main
    workflow.run()
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 217, in _run
    cns_input = self.prepare_cns_input_parallel(
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 164, in prepare_cns_input_parallel
    assert isinstance(prepare_engine, Scheduler)
AssertionError
[2024-07-16 10:51:12,759 libutil ERROR]
```

**To Reproduce**

Run one of the example in MPI mode.

**Comment by rvhonorato** [comment]
This is not a bug, this assert is there to catch exactly this scenario
